// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: driver_document_type.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
)

const countDriverDocumentTypes = `-- name: CountDriverDocumentTypes :one
SELECT COUNT(*) FROM driver_document_types
WHERE deleted_at IS NULL
  AND ($1 = '' OR name ILIKE '%' || $1 || '%' OR code ILIKE '%' || $1 || '%')
`

func (q *Queries) CountDriverDocumentTypes(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countDriverDocumentTypes, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDriverDocumentTypesByServiceID = `-- name: CountDriverDocumentTypesByServiceID :one
SELECT COUNT(*) FROM driver_document_types
WHERE deleted_at IS NULL AND service_id = $1
  AND ($2 = '' OR name ILIKE '%' || $2 || '%' OR code ILIKE '%' || $2 || '%')
`

type CountDriverDocumentTypesByServiceIDParams struct {
	ServiceID *uuid.UUID  `json:"service_id"`
	Column2   interface{} `json:"column_2"`
}

func (q *Queries) CountDriverDocumentTypesByServiceID(ctx context.Context, arg CountDriverDocumentTypesByServiceIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDriverDocumentTypesByServiceID, arg.ServiceID, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDriverDocumentType = `-- name: CreateDriverDocumentType :one
INSERT INTO driver_document_types (
  code,
  name,
  description,
  is_required,
  require_expire_date,
  service_id,
  is_active
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, code, name, description, is_required, require_expire_date, service_id, is_active, created_at, deleted_at
`

type CreateDriverDocumentTypeParams struct {
	Code              string     `json:"code"`
	Name              string     `json:"name"`
	Description       string     `json:"description"`
	IsRequired        bool       `json:"is_required"`
	RequireExpireDate bool       `json:"require_expire_date"`
	ServiceID         *uuid.UUID `json:"service_id"`
	IsActive          bool       `json:"is_active"`
}

func (q *Queries) CreateDriverDocumentType(ctx context.Context, arg CreateDriverDocumentTypeParams) (DriverDocumentType, error) {
	row := q.db.QueryRow(ctx, createDriverDocumentType,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.IsRequired,
		arg.RequireExpireDate,
		arg.ServiceID,
		arg.IsActive,
	)
	var i DriverDocumentType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsRequired,
		&i.RequireExpireDate,
		&i.ServiceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDriverDocumentType = `-- name: DeleteDriverDocumentType :exec
UPDATE driver_document_types
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteDriverDocumentType(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDriverDocumentType, id)
	return err
}

const getDriverDocumentTypeByCodeAndServiceID = `-- name: GetDriverDocumentTypeByCodeAndServiceID :one
SELECT id, code, name, description, is_required, require_expire_date, service_id, is_active, created_at, deleted_at FROM driver_document_types
WHERE code = $1 AND service_id = $2 AND deleted_at IS NULL
`

type GetDriverDocumentTypeByCodeAndServiceIDParams struct {
	Code      string     `json:"code"`
	ServiceID *uuid.UUID `json:"service_id"`
}

func (q *Queries) GetDriverDocumentTypeByCodeAndServiceID(ctx context.Context, arg GetDriverDocumentTypeByCodeAndServiceIDParams) (DriverDocumentType, error) {
	row := q.db.QueryRow(ctx, getDriverDocumentTypeByCodeAndServiceID, arg.Code, arg.ServiceID)
	var i DriverDocumentType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsRequired,
		&i.RequireExpireDate,
		&i.ServiceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDriverDocumentTypeByCodeGlobal = `-- name: GetDriverDocumentTypeByCodeGlobal :one
SELECT id, code, name, description, is_required, require_expire_date, service_id, is_active, created_at, deleted_at FROM driver_document_types
WHERE code = $1 AND service_id IS NULL AND deleted_at IS NULL
`

func (q *Queries) GetDriverDocumentTypeByCodeGlobal(ctx context.Context, code string) (DriverDocumentType, error) {
	row := q.db.QueryRow(ctx, getDriverDocumentTypeByCodeGlobal, code)
	var i DriverDocumentType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsRequired,
		&i.RequireExpireDate,
		&i.ServiceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDriverDocumentTypeByID = `-- name: GetDriverDocumentTypeByID :one
SELECT id, code, name, description, is_required, require_expire_date, service_id, is_active, created_at, deleted_at FROM driver_document_types
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDriverDocumentTypeByID(ctx context.Context, id uuid.UUID) (DriverDocumentType, error) {
	row := q.db.QueryRow(ctx, getDriverDocumentTypeByID, id)
	var i DriverDocumentType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsRequired,
		&i.RequireExpireDate,
		&i.ServiceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDriverDocumentTypes = `-- name: ListDriverDocumentTypes :many
SELECT id, code, name, description, is_required, require_expire_date, service_id, is_active, created_at, deleted_at FROM driver_document_types
WHERE deleted_at IS NULL
  AND ($1 = '' OR name ILIKE '%' || $1 || '%' OR code ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDriverDocumentTypesParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListDriverDocumentTypes(ctx context.Context, arg ListDriverDocumentTypesParams) ([]DriverDocumentType, error) {
	rows, err := q.db.Query(ctx, listDriverDocumentTypes, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriverDocumentType{}
	for rows.Next() {
		var i DriverDocumentType
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsRequired,
			&i.RequireExpireDate,
			&i.ServiceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDriverDocumentTypesByServiceID = `-- name: ListDriverDocumentTypesByServiceID :many
SELECT id, code, name, description, is_required, require_expire_date, service_id, is_active, created_at, deleted_at FROM driver_document_types
WHERE deleted_at IS NULL AND service_id = $1
  AND ($2 = '' OR name ILIKE '%' || $2 || '%' OR code ILIKE '%' || $2 || '%')
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListDriverDocumentTypesByServiceIDParams struct {
	ServiceID *uuid.UUID  `json:"service_id"`
	Column2   interface{} `json:"column_2"`
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
}

func (q *Queries) ListDriverDocumentTypesByServiceID(ctx context.Context, arg ListDriverDocumentTypesByServiceIDParams) ([]DriverDocumentType, error) {
	rows, err := q.db.Query(ctx, listDriverDocumentTypesByServiceID,
		arg.ServiceID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriverDocumentType{}
	for rows.Next() {
		var i DriverDocumentType
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsRequired,
			&i.RequireExpireDate,
			&i.ServiceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRequiredDriverDocumentTypesByServiceID = `-- name: ListRequiredDriverDocumentTypesByServiceID :many
SELECT id, code, name, description, is_required, require_expire_date, service_id, is_active, created_at, deleted_at FROM driver_document_types
WHERE deleted_at IS NULL
  AND is_active = true
  AND (service_id = $1 OR service_id IS NULL)
ORDER BY service_id NULLS LAST, created_at ASC
`

// Trả về document types áp dụng cho service: theo service_id HOẶC chung (service_id IS NULL), chỉ lấy bản ghi đang active.
func (q *Queries) ListRequiredDriverDocumentTypesByServiceID(ctx context.Context, serviceID *uuid.UUID) ([]DriverDocumentType, error) {
	rows, err := q.db.Query(ctx, listRequiredDriverDocumentTypesByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriverDocumentType{}
	for rows.Next() {
		var i DriverDocumentType
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsRequired,
			&i.RequireExpireDate,
			&i.ServiceID,
			&i.IsActive,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDriverDocumentType = `-- name: UpdateDriverDocumentType :one
UPDATE driver_document_types
SET
  code = $2,
  name = $3,
  description = $4,
  is_required = $5,
  require_expire_date = $6,
  service_id = $7,
  is_active = $8
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, name, description, is_required, require_expire_date, service_id, is_active, created_at, deleted_at
`

type UpdateDriverDocumentTypeParams struct {
	ID                uuid.UUID  `json:"id"`
	Code              string     `json:"code"`
	Name              string     `json:"name"`
	Description       string     `json:"description"`
	IsRequired        bool       `json:"is_required"`
	RequireExpireDate bool       `json:"require_expire_date"`
	ServiceID         *uuid.UUID `json:"service_id"`
	IsActive          bool       `json:"is_active"`
}

func (q *Queries) UpdateDriverDocumentType(ctx context.Context, arg UpdateDriverDocumentTypeParams) (DriverDocumentType, error) {
	row := q.db.QueryRow(ctx, updateDriverDocumentType,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.IsRequired,
		arg.RequireExpireDate,
		arg.ServiceID,
		arg.IsActive,
	)
	var i DriverDocumentType
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsRequired,
		&i.RequireExpireDate,
		&i.ServiceID,
		&i.IsActive,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
