// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: driver_profile.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countDriverProfiles = `-- name: CountDriverProfiles :one
SELECT COUNT(*) FROM driver_profiles
WHERE deleted_at IS NULL
  AND ($1 = '' OR full_name ILIKE '%' || $1 || '%')
  AND ($2 = '' OR global_status = $2::driver_profile_status)
`

type CountDriverProfilesParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) CountDriverProfiles(ctx context.Context, arg CountDriverProfilesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDriverProfiles, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDriverProfile = `-- name: CreateDriverProfile :one
INSERT INTO driver_profiles (
    account_id,
    full_name,
    date_of_birth,
    gender,
    address,
    global_status
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, account_id, full_name, date_of_birth, gender, address, global_status, rating, total_completed_orders, created_at, updated_at, deleted_at
`

type CreateDriverProfileParams struct {
	AccountID    uuid.UUID           `json:"account_id"`
	FullName     string              `json:"full_name"`
	DateOfBirth  pgtype.Date         `json:"date_of_birth"`
	Gender       pgtype.Text         `json:"gender"`
	Address      pgtype.Text         `json:"address"`
	GlobalStatus DriverProfileStatus `json:"global_status"`
}

func (q *Queries) CreateDriverProfile(ctx context.Context, arg CreateDriverProfileParams) (DriverProfile, error) {
	row := q.db.QueryRow(ctx, createDriverProfile,
		arg.AccountID,
		arg.FullName,
		arg.DateOfBirth,
		arg.Gender,
		arg.Address,
		arg.GlobalStatus,
	)
	var i DriverProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.GlobalStatus,
		&i.Rating,
		&i.TotalCompletedOrders,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDriverProfile = `-- name: DeleteDriverProfile :exec
UPDATE driver_profiles
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteDriverProfile(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDriverProfile, id)
	return err
}

const getDriverProfileByAccountID = `-- name: GetDriverProfileByAccountID :one
SELECT id, account_id, full_name, date_of_birth, gender, address, global_status, rating, total_completed_orders, created_at, updated_at, deleted_at FROM driver_profiles
WHERE account_id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetDriverProfileByAccountID(ctx context.Context, accountID uuid.UUID) (DriverProfile, error) {
	row := q.db.QueryRow(ctx, getDriverProfileByAccountID, accountID)
	var i DriverProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.GlobalStatus,
		&i.Rating,
		&i.TotalCompletedOrders,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDriverProfileByID = `-- name: GetDriverProfileByID :one
SELECT id, account_id, full_name, date_of_birth, gender, address, global_status, rating, total_completed_orders, created_at, updated_at, deleted_at FROM driver_profiles
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetDriverProfileByID(ctx context.Context, id uuid.UUID) (DriverProfile, error) {
	row := q.db.QueryRow(ctx, getDriverProfileByID, id)
	var i DriverProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.GlobalStatus,
		&i.Rating,
		&i.TotalCompletedOrders,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDriverProfiles = `-- name: ListDriverProfiles :many
SELECT id, account_id, full_name, date_of_birth, gender, address, global_status, rating, total_completed_orders, created_at, updated_at, deleted_at FROM driver_profiles
WHERE deleted_at IS NULL
  AND ($1 = '' OR full_name ILIKE '%' || $1 || '%')
  AND ($2 = '' OR global_status = $2::driver_profile_status)
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListDriverProfilesParams struct {
	Column1 interface{} `json:"column_1"`
	Column2 interface{} `json:"column_2"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListDriverProfiles(ctx context.Context, arg ListDriverProfilesParams) ([]DriverProfile, error) {
	rows, err := q.db.Query(ctx, listDriverProfiles,
		arg.Column1,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriverProfile{}
	for rows.Next() {
		var i DriverProfile
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.FullName,
			&i.DateOfBirth,
			&i.Gender,
			&i.Address,
			&i.GlobalStatus,
			&i.Rating,
			&i.TotalCompletedOrders,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDriverProfile = `-- name: UpdateDriverProfile :one
UPDATE driver_profiles
SET
    full_name = COALESCE($1, full_name),
    date_of_birth = COALESCE($2, date_of_birth),
    gender = COALESCE($3, gender),
    address = COALESCE($4, address),
    global_status = COALESCE($5, global_status),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, account_id, full_name, date_of_birth, gender, address, global_status, rating, total_completed_orders, created_at, updated_at, deleted_at
`

type UpdateDriverProfileParams struct {
	FullName     pgtype.Text             `json:"full_name"`
	DateOfBirth  pgtype.Date             `json:"date_of_birth"`
	Gender       pgtype.Text             `json:"gender"`
	Address      pgtype.Text             `json:"address"`
	GlobalStatus NullDriverProfileStatus `json:"global_status"`
	ID           uuid.UUID               `json:"id"`
}

func (q *Queries) UpdateDriverProfile(ctx context.Context, arg UpdateDriverProfileParams) (DriverProfile, error) {
	row := q.db.QueryRow(ctx, updateDriverProfile,
		arg.FullName,
		arg.DateOfBirth,
		arg.Gender,
		arg.Address,
		arg.GlobalStatus,
		arg.ID,
	)
	var i DriverProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.GlobalStatus,
		&i.Rating,
		&i.TotalCompletedOrders,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
