root = "."
tmp_dir = "cmd/tmp"

[build]
  cmd = "go build -tags=dev -trimpath -o cmd/tmp/app ./cmd/server"
  bin = "cmd/tmp/app"
  delay = 300
  poll = false
  send_interrupt = true
  kill_delay = 500

  include_ext = ["go"]

  include_dir = [
    "cmd",
    "internal",
    "pkg",
    "config",
    "global",
    "orm"
  ]

  exclude_dir = [
    "cmd/tmp",
    "vendor",
    "docs",
    "docs-api",
    "docs-internal",
    "node_modules",
    "storage",
    "storage/logs",
    "scripts",
    "docker",
    "orm/postgres/migrations",
    ".git"
  ]

[log]
  time = true

[misc]
  clean_on_exit = true