// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_app_device.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccountAppDevice = `-- name: CreateAccountAppDevice :one
INSERT INTO account_app_devices (
    account_id,
    device_id,
    app_type,
    fcm_token,
    is_active,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, account_id, device_id, app_type, fcm_token, is_active, last_used_at, metadata, created_at, updated_at, deleted_at
`

type CreateAccountAppDeviceParams struct {
	AccountID uuid.UUID   `json:"account_id"`
	DeviceID  uuid.UUID   `json:"device_id"`
	AppType   string      `json:"app_type"`
	FcmToken  pgtype.Text `json:"fcm_token"`
	IsActive  bool        `json:"is_active"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) CreateAccountAppDevice(ctx context.Context, arg CreateAccountAppDeviceParams) (AccountAppDevice, error) {
	row := q.db.QueryRow(ctx, createAccountAppDevice,
		arg.AccountID,
		arg.DeviceID,
		arg.AppType,
		arg.FcmToken,
		arg.IsActive,
		arg.Metadata,
	)
	var i AccountAppDevice
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.DeviceID,
		&i.AppType,
		&i.FcmToken,
		&i.IsActive,
		&i.LastUsedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAccountAppDevice = `-- name: DeleteAccountAppDevice :exec
UPDATE account_app_devices
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeleteAccountAppDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccountAppDevice, id)
	return err
}

const getAccountAppDevice = `-- name: GetAccountAppDevice :one
SELECT id, account_id, device_id, app_type, fcm_token, is_active, last_used_at, metadata, created_at, updated_at, deleted_at FROM account_app_devices
WHERE account_id = $1
  AND device_id = $2
  AND app_type = $3
  AND deleted_at IS NULL
`

type GetAccountAppDeviceParams struct {
	AccountID uuid.UUID `json:"account_id"`
	DeviceID  uuid.UUID `json:"device_id"`
	AppType   string    `json:"app_type"`
}

func (q *Queries) GetAccountAppDevice(ctx context.Context, arg GetAccountAppDeviceParams) (AccountAppDevice, error) {
	row := q.db.QueryRow(ctx, getAccountAppDevice, arg.AccountID, arg.DeviceID, arg.AppType)
	var i AccountAppDevice
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.DeviceID,
		&i.AppType,
		&i.FcmToken,
		&i.IsActive,
		&i.LastUsedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAccountAppDeviceByID = `-- name: GetAccountAppDeviceByID :one
SELECT id, account_id, device_id, app_type, fcm_token, is_active, last_used_at, metadata, created_at, updated_at, deleted_at FROM account_app_devices
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetAccountAppDeviceByID(ctx context.Context, id uuid.UUID) (AccountAppDevice, error) {
	row := q.db.QueryRow(ctx, getAccountAppDeviceByID, id)
	var i AccountAppDevice
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.DeviceID,
		&i.AppType,
		&i.FcmToken,
		&i.IsActive,
		&i.LastUsedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAccountAppDevices = `-- name: ListAccountAppDevices :many
SELECT id, account_id, device_id, app_type, fcm_token, is_active, last_used_at, metadata, created_at, updated_at, deleted_at FROM account_app_devices
WHERE account_id = $1 AND deleted_at IS NULL
ORDER BY last_used_at DESC NULLS LAST, created_at DESC
`

func (q *Queries) ListAccountAppDevices(ctx context.Context, accountID uuid.UUID) ([]AccountAppDevice, error) {
	rows, err := q.db.Query(ctx, listAccountAppDevices, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AccountAppDevice{}
	for rows.Next() {
		var i AccountAppDevice
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.DeviceID,
			&i.AppType,
			&i.FcmToken,
			&i.IsActive,
			&i.LastUsedAt,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountAppDevice = `-- name: UpdateAccountAppDevice :one
UPDATE account_app_devices
SET
    fcm_token = COALESCE($2, fcm_token),
    is_active = COALESCE($3, is_active),
    last_used_at = COALESCE($4, last_used_at),
    metadata = COALESCE($5, metadata),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, account_id, device_id, app_type, fcm_token, is_active, last_used_at, metadata, created_at, updated_at, deleted_at
`

type UpdateAccountAppDeviceParams struct {
	ID         uuid.UUID          `json:"id"`
	FcmToken   pgtype.Text        `json:"fcm_token"`
	IsActive   pgtype.Bool        `json:"is_active"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	Metadata   []byte             `json:"metadata"`
}

func (q *Queries) UpdateAccountAppDevice(ctx context.Context, arg UpdateAccountAppDeviceParams) (AccountAppDevice, error) {
	row := q.db.QueryRow(ctx, updateAccountAppDevice,
		arg.ID,
		arg.FcmToken,
		arg.IsActive,
		arg.LastUsedAt,
		arg.Metadata,
	)
	var i AccountAppDevice
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.DeviceID,
		&i.AppType,
		&i.FcmToken,
		&i.IsActive,
		&i.LastUsedAt,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
