// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: device.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDevice = `-- name: CreateDevice :one
INSERT INTO devices (
    device_uid,
    platform,
    device_name,
    os_version,
    app_version,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, device_uid, platform, device_name, os_version, app_version, metadata, created_at, updated_at, deleted_at
`

type CreateDeviceParams struct {
	DeviceUid  string      `json:"device_uid"`
	Platform   string      `json:"platform"`
	DeviceName pgtype.Text `json:"device_name"`
	OsVersion  pgtype.Text `json:"os_version"`
	AppVersion pgtype.Text `json:"app_version"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, createDevice,
		arg.DeviceUid,
		arg.Platform,
		arg.DeviceName,
		arg.OsVersion,
		arg.AppVersion,
		arg.Metadata,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceUid,
		&i.Platform,
		&i.DeviceName,
		&i.OsVersion,
		&i.AppVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDevice = `-- name: DeleteDevice :exec
UPDATE devices
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) DeleteDevice(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDevice, id)
	return err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, device_uid, platform, device_name, os_version, app_version, metadata, created_at, updated_at, deleted_at FROM devices
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDeviceByID(ctx context.Context, id uuid.UUID) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceUid,
		&i.Platform,
		&i.DeviceName,
		&i.OsVersion,
		&i.AppVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDeviceByUID = `-- name: GetDeviceByUID :one
SELECT id, device_uid, platform, device_name, os_version, app_version, metadata, created_at, updated_at, deleted_at FROM devices
WHERE device_uid = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDeviceByUID(ctx context.Context, deviceUid string) (Device, error) {
	row := q.db.QueryRow(ctx, getDeviceByUID, deviceUid)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceUid,
		&i.Platform,
		&i.DeviceName,
		&i.OsVersion,
		&i.AppVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDevice = `-- name: UpdateDevice :one
UPDATE devices
SET
    device_name = COALESCE($2, device_name),
    os_version = COALESCE($3, os_version),
    app_version = COALESCE($4, app_version),
    metadata = COALESCE($5, metadata),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, device_uid, platform, device_name, os_version, app_version, metadata, created_at, updated_at, deleted_at
`

type UpdateDeviceParams struct {
	ID         uuid.UUID   `json:"id"`
	DeviceName pgtype.Text `json:"device_name"`
	OsVersion  pgtype.Text `json:"os_version"`
	AppVersion pgtype.Text `json:"app_version"`
	Metadata   []byte      `json:"metadata"`
}

func (q *Queries) UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error) {
	row := q.db.QueryRow(ctx, updateDevice,
		arg.ID,
		arg.DeviceName,
		arg.OsVersion,
		arg.AppVersion,
		arg.Metadata,
	)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.DeviceUid,
		&i.Platform,
		&i.DeviceName,
		&i.OsVersion,
		&i.AppVersion,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
