// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: distance_pricing_rules.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDistancePricingRule = `-- name: CreateDistancePricingRule :one
INSERT INTO system_distance_pricing_rules (service_id, from_km, to_km, price_per_km, is_active)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, service_id, from_km, to_km, price_per_km, is_active, created_at, updated_at, deleted_at
`

type CreateDistancePricingRuleParams struct {
	ServiceID  uuid.UUID      `json:"service_id"`
	FromKm     pgtype.Numeric `json:"from_km"`
	ToKm       pgtype.Numeric `json:"to_km"`
	PricePerKm pgtype.Numeric `json:"price_per_km"`
	IsActive   bool           `json:"is_active"`
}

func (q *Queries) CreateDistancePricingRule(ctx context.Context, arg CreateDistancePricingRuleParams) (SystemDistancePricingRule, error) {
	row := q.db.QueryRow(ctx, createDistancePricingRule,
		arg.ServiceID,
		arg.FromKm,
		arg.ToKm,
		arg.PricePerKm,
		arg.IsActive,
	)
	var i SystemDistancePricingRule
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.FromKm,
		&i.ToKm,
		&i.PricePerKm,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDistancePricingRule = `-- name: DeleteDistancePricingRule :exec
UPDATE system_distance_pricing_rules
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteDistancePricingRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDistancePricingRule, id)
	return err
}

const getDistancePricingRuleByID = `-- name: GetDistancePricingRuleByID :one
SELECT id, service_id, from_km, to_km, price_per_km, is_active, created_at, updated_at, deleted_at FROM system_distance_pricing_rules
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDistancePricingRuleByID(ctx context.Context, id uuid.UUID) (SystemDistancePricingRule, error) {
	row := q.db.QueryRow(ctx, getDistancePricingRuleByID, id)
	var i SystemDistancePricingRule
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.FromKm,
		&i.ToKm,
		&i.PricePerKm,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDistancePricingRules = `-- name: ListDistancePricingRules :many
SELECT id, service_id, from_km, to_km, price_per_km, is_active, created_at, updated_at, deleted_at FROM system_distance_pricing_rules
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR service_id = $1::uuid)
ORDER BY service_id ASC, from_km ASC
`

func (q *Queries) ListDistancePricingRules(ctx context.Context, serviceID pgtype.UUID) ([]SystemDistancePricingRule, error) {
	rows, err := q.db.Query(ctx, listDistancePricingRules, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemDistancePricingRule{}
	for rows.Next() {
		var i SystemDistancePricingRule
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.FromKm,
			&i.ToKm,
			&i.PricePerKm,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDistancePricingRulesByServiceID = `-- name: ListDistancePricingRulesByServiceID :many
SELECT id, service_id, from_km, to_km, price_per_km, is_active, created_at, updated_at, deleted_at FROM system_distance_pricing_rules
WHERE service_id = $1 AND deleted_at IS NULL
ORDER BY from_km ASC
`

func (q *Queries) ListDistancePricingRulesByServiceID(ctx context.Context, serviceID uuid.UUID) ([]SystemDistancePricingRule, error) {
	rows, err := q.db.Query(ctx, listDistancePricingRulesByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemDistancePricingRule{}
	for rows.Next() {
		var i SystemDistancePricingRule
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.FromKm,
			&i.ToKm,
			&i.PricePerKm,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDistancePricingRule = `-- name: UpdateDistancePricingRule :one
UPDATE system_distance_pricing_rules
SET
  service_id = $2,
  from_km = $3,
  to_km = $4,
  price_per_km = $5,
  is_active = $6,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, service_id, from_km, to_km, price_per_km, is_active, created_at, updated_at, deleted_at
`

type UpdateDistancePricingRuleParams struct {
	ID         uuid.UUID      `json:"id"`
	ServiceID  uuid.UUID      `json:"service_id"`
	FromKm     pgtype.Numeric `json:"from_km"`
	ToKm       pgtype.Numeric `json:"to_km"`
	PricePerKm pgtype.Numeric `json:"price_per_km"`
	IsActive   bool           `json:"is_active"`
}

func (q *Queries) UpdateDistancePricingRule(ctx context.Context, arg UpdateDistancePricingRuleParams) (SystemDistancePricingRule, error) {
	row := q.db.QueryRow(ctx, updateDistancePricingRule,
		arg.ID,
		arg.ServiceID,
		arg.FromKm,
		arg.ToKm,
		arg.PricePerKm,
		arg.IsActive,
	)
	var i SystemDistancePricingRule
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.FromKm,
		&i.ToKm,
		&i.PricePerKm,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
