// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: driver_document.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDriverDocument = `-- name: CreateDriverDocument :one
INSERT INTO driver_documents (
  driver_id,
  document_type_id,
  file_url,
  expire_at,
  status
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, driver_id, document_type_id, file_url, expire_at, status, reject_reason, verified_at, verified_by, created_at, updated_at, deleted_at
`

type CreateDriverDocumentParams struct {
	DriverID       uuid.UUID            `json:"driver_id"`
	DocumentTypeID uuid.UUID            `json:"document_type_id"`
	FileUrl        string               `json:"file_url"`
	ExpireAt       pgtype.Date          `json:"expire_at"`
	Status         DriverDocumentStatus `json:"status"`
}

func (q *Queries) CreateDriverDocument(ctx context.Context, arg CreateDriverDocumentParams) (DriverDocument, error) {
	row := q.db.QueryRow(ctx, createDriverDocument,
		arg.DriverID,
		arg.DocumentTypeID,
		arg.FileUrl,
		arg.ExpireAt,
		arg.Status,
	)
	var i DriverDocument
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.DocumentTypeID,
		&i.FileUrl,
		&i.ExpireAt,
		&i.Status,
		&i.RejectReason,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteDriverDocument = `-- name: DeleteDriverDocument :exec
UPDATE driver_documents
SET deleted_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteDriverDocument(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDriverDocument, id)
	return err
}

const getDriverDocumentByID = `-- name: GetDriverDocumentByID :one
SELECT id, driver_id, document_type_id, file_url, expire_at, status, reject_reason, verified_at, verified_by, created_at, updated_at, deleted_at FROM driver_documents
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetDriverDocumentByID(ctx context.Context, id uuid.UUID) (DriverDocument, error) {
	row := q.db.QueryRow(ctx, getDriverDocumentByID, id)
	var i DriverDocument
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.DocumentTypeID,
		&i.FileUrl,
		&i.ExpireAt,
		&i.Status,
		&i.RejectReason,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listDriverDocumentsByDriverID = `-- name: ListDriverDocumentsByDriverID :many
SELECT id, driver_id, document_type_id, file_url, expire_at, status, reject_reason, verified_at, verified_by, created_at, updated_at, deleted_at FROM driver_documents
WHERE driver_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListDriverDocumentsByDriverID(ctx context.Context, driverID uuid.UUID) ([]DriverDocument, error) {
	rows, err := q.db.Query(ctx, listDriverDocumentsByDriverID, driverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DriverDocument{}
	for rows.Next() {
		var i DriverDocument
		if err := rows.Scan(
			&i.ID,
			&i.DriverID,
			&i.DocumentTypeID,
			&i.FileUrl,
			&i.ExpireAt,
			&i.Status,
			&i.RejectReason,
			&i.VerifiedAt,
			&i.VerifiedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDriverDocument = `-- name: UpdateDriverDocument :one
UPDATE driver_documents
SET
  file_url = $2,
  expire_at = $3,
  status = $4,
  reject_reason = $5,
  verified_at = $6,
  verified_by = $7,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, driver_id, document_type_id, file_url, expire_at, status, reject_reason, verified_at, verified_by, created_at, updated_at, deleted_at
`

type UpdateDriverDocumentParams struct {
	ID           uuid.UUID            `json:"id"`
	FileUrl      string               `json:"file_url"`
	ExpireAt     pgtype.Date          `json:"expire_at"`
	Status       DriverDocumentStatus `json:"status"`
	RejectReason pgtype.Text          `json:"reject_reason"`
	VerifiedAt   pgtype.Timestamptz   `json:"verified_at"`
	VerifiedBy   pgtype.UUID          `json:"verified_by"`
}

func (q *Queries) UpdateDriverDocument(ctx context.Context, arg UpdateDriverDocumentParams) (DriverDocument, error) {
	row := q.db.QueryRow(ctx, updateDriverDocument,
		arg.ID,
		arg.FileUrl,
		arg.ExpireAt,
		arg.Status,
		arg.RejectReason,
		arg.VerifiedAt,
		arg.VerifiedBy,
	)
	var i DriverDocument
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.DocumentTypeID,
		&i.FileUrl,
		&i.ExpireAt,
		&i.Status,
		&i.RejectReason,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDriverDocumentPartial = `-- name: UpdateDriverDocumentPartial :one
UPDATE driver_documents
SET
  file_url = COALESCE($1, file_url),
  expire_at = COALESCE($2, expire_at),
  status = COALESCE($3, status),
  reject_reason = COALESCE($4, reject_reason),
  updated_at = CURRENT_TIMESTAMP
WHERE id = $5 AND deleted_at IS NULL
RETURNING id, driver_id, document_type_id, file_url, expire_at, status, reject_reason, verified_at, verified_by, created_at, updated_at, deleted_at
`

type UpdateDriverDocumentPartialParams struct {
	FileUrl      pgtype.Text              `json:"file_url"`
	ExpireAt     pgtype.Date              `json:"expire_at"`
	Status       NullDriverDocumentStatus `json:"status"`
	RejectReason pgtype.Text              `json:"reject_reason"`
	ID           uuid.UUID                `json:"id"`
}

// Bulk update (PATCH): chỉ cập nhật các field được truyền (khác NULL).
func (q *Queries) UpdateDriverDocumentPartial(ctx context.Context, arg UpdateDriverDocumentPartialParams) (DriverDocument, error) {
	row := q.db.QueryRow(ctx, updateDriverDocumentPartial,
		arg.FileUrl,
		arg.ExpireAt,
		arg.Status,
		arg.RejectReason,
		arg.ID,
	)
	var i DriverDocument
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.DocumentTypeID,
		&i.FileUrl,
		&i.ExpireAt,
		&i.Status,
		&i.RejectReason,
		&i.VerifiedAt,
		&i.VerifiedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
