// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: driver_profile_status_history.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDriverProfileStatusHistory = `-- name: CreateDriverProfileStatusHistory :one
INSERT INTO driver_profile_status_histories (driver_id, from_status, to_status, changed_by, reason)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, driver_id, from_status, to_status, changed_by, reason, created_at, deleted_at
`

type CreateDriverProfileStatusHistoryParams struct {
	DriverID   uuid.UUID               `json:"driver_id"`
	FromStatus NullDriverProfileStatus `json:"from_status"`
	ToStatus   DriverProfileStatus     `json:"to_status"`
	ChangedBy  pgtype.UUID             `json:"changed_by"`
	Reason     pgtype.Text             `json:"reason"`
}

func (q *Queries) CreateDriverProfileStatusHistory(ctx context.Context, arg CreateDriverProfileStatusHistoryParams) (DriverProfileStatusHistory, error) {
	row := q.db.QueryRow(ctx, createDriverProfileStatusHistory,
		arg.DriverID,
		arg.FromStatus,
		arg.ToStatus,
		arg.ChangedBy,
		arg.Reason,
	)
	var i DriverProfileStatusHistory
	err := row.Scan(
		&i.ID,
		&i.DriverID,
		&i.FromStatus,
		&i.ToStatus,
		&i.ChangedBy,
		&i.Reason,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}
