// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: driver_profile.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDriverProfile = `-- name: CreateDriverProfile :one
INSERT INTO driver_profiles (
    account_id,
    full_name,
    date_of_birth,
    gender,
    address,
    global_status
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, account_id, full_name, date_of_birth, gender, address, global_status, rating, total_completed_orders, created_at, updated_at, deleted_at
`

type CreateDriverProfileParams struct {
	AccountID    uuid.UUID           `json:"account_id"`
	FullName     string              `json:"full_name"`
	DateOfBirth  pgtype.Date         `json:"date_of_birth"`
	Gender       pgtype.Text         `json:"gender"`
	Address      pgtype.Text         `json:"address"`
	GlobalStatus DriverProfileStatus `json:"global_status"`
}

func (q *Queries) CreateDriverProfile(ctx context.Context, arg CreateDriverProfileParams) (DriverProfile, error) {
	row := q.db.QueryRow(ctx, createDriverProfile,
		arg.AccountID,
		arg.FullName,
		arg.DateOfBirth,
		arg.Gender,
		arg.Address,
		arg.GlobalStatus,
	)
	var i DriverProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.GlobalStatus,
		&i.Rating,
		&i.TotalCompletedOrders,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDriverProfileByAccountID = `-- name: GetDriverProfileByAccountID :one
SELECT id, account_id, full_name, date_of_birth, gender, address, global_status, rating, total_completed_orders, created_at, updated_at, deleted_at FROM driver_profiles
WHERE account_id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetDriverProfileByAccountID(ctx context.Context, accountID uuid.UUID) (DriverProfile, error) {
	row := q.db.QueryRow(ctx, getDriverProfileByAccountID, accountID)
	var i DriverProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.GlobalStatus,
		&i.Rating,
		&i.TotalCompletedOrders,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getDriverProfileByID = `-- name: GetDriverProfileByID :one
SELECT id, account_id, full_name, date_of_birth, gender, address, global_status, rating, total_completed_orders, created_at, updated_at, deleted_at FROM driver_profiles
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetDriverProfileByID(ctx context.Context, id uuid.UUID) (DriverProfile, error) {
	row := q.db.QueryRow(ctx, getDriverProfileByID, id)
	var i DriverProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.GlobalStatus,
		&i.Rating,
		&i.TotalCompletedOrders,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateDriverProfile = `-- name: UpdateDriverProfile :one
UPDATE driver_profiles
SET
    full_name = COALESCE($1, full_name),
    date_of_birth = COALESCE($2, date_of_birth),
    gender = COALESCE($3, gender),
    address = COALESCE($4, address),
    global_status = COALESCE($5, global_status),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, account_id, full_name, date_of_birth, gender, address, global_status, rating, total_completed_orders, created_at, updated_at, deleted_at
`

type UpdateDriverProfileParams struct {
	FullName     pgtype.Text             `json:"full_name"`
	DateOfBirth  pgtype.Date             `json:"date_of_birth"`
	Gender       pgtype.Text             `json:"gender"`
	Address      pgtype.Text             `json:"address"`
	GlobalStatus NullDriverProfileStatus `json:"global_status"`
	ID           uuid.UUID               `json:"id"`
}

func (q *Queries) UpdateDriverProfile(ctx context.Context, arg UpdateDriverProfileParams) (DriverProfile, error) {
	row := q.db.QueryRow(ctx, updateDriverProfile,
		arg.FullName,
		arg.DateOfBirth,
		arg.Gender,
		arg.Address,
		arg.GlobalStatus,
		arg.ID,
	)
	var i DriverProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.FullName,
		&i.DateOfBirth,
		&i.Gender,
		&i.Address,
		&i.GlobalStatus,
		&i.Rating,
		&i.TotalCompletedOrders,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
