// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: login_history.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLoginHistory = `-- name: CreateLoginHistory :one
INSERT INTO login_histories (
    account_id,
    device_id,
    app_type,
    result,
    failure_reason,
    ip_address,
    user_agent,
    location,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, account_id, device_id, app_type, login_at, result, failure_reason, ip_address, user_agent, location, metadata, created_at
`

type CreateLoginHistoryParams struct {
	AccountID     uuid.UUID   `json:"account_id"`
	DeviceID      uuid.UUID   `json:"device_id"`
	AppType       string      `json:"app_type"`
	Result        string      `json:"result"`
	FailureReason pgtype.Text `json:"failure_reason"`
	IpAddress     pgtype.Text `json:"ip_address"`
	UserAgent     pgtype.Text `json:"user_agent"`
	Location      pgtype.Text `json:"location"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) CreateLoginHistory(ctx context.Context, arg CreateLoginHistoryParams) (LoginHistory, error) {
	row := q.db.QueryRow(ctx, createLoginHistory,
		arg.AccountID,
		arg.DeviceID,
		arg.AppType,
		arg.Result,
		arg.FailureReason,
		arg.IpAddress,
		arg.UserAgent,
		arg.Location,
		arg.Metadata,
	)
	var i LoginHistory
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.DeviceID,
		&i.AppType,
		&i.LoginAt,
		&i.Result,
		&i.FailureReason,
		&i.IpAddress,
		&i.UserAgent,
		&i.Location,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
