// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID           uuid.UUID          `json:"id"`
	Email        pgtype.Text        `json:"email"`
	Phone        string             `json:"phone"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Otp struct {
	ID           uuid.UUID        `json:"id"`
	Target       string           `json:"target"`
	OtpCode      string           `json:"otp_code"`
	Purpose      string           `json:"purpose"`
	AttemptCount pgtype.Int4      `json:"attempt_count"`
	MaxAttempt   pgtype.Int4      `json:"max_attempt"`
	ExpiresAt    pgtype.Timestamp `json:"expires_at"`
	UsedAt       pgtype.Timestamp `json:"used_at"`
	Status       pgtype.Text      `json:"status"`
	Metadata     []byte           `json:"metadata"`
	CreatedAt    pgtype.Timestamp `json:"created_at"`
	UpdatedAt    pgtype.Timestamp `json:"updated_at"`
}

type UserProfile struct {
	ID        uuid.UUID        `json:"id"`
	AccountID uuid.UUID        `json:"account_id"`
	FullName  string           `json:"full_name"`
	AvatarUrl pgtype.Text      `json:"avatar_url"`
	IsActive  pgtype.Bool      `json:"is_active"`
	Metadata  []byte           `json:"metadata"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
	UpdatedAt pgtype.Timestamp `json:"updated_at"`
}
