// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otp.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countOTPsCreatedSince = `-- name: CountOTPsCreatedSince :one
SELECT COUNT(*)::int FROM otps
WHERE target = $1 AND purpose = $2 AND created_at >= $3
`

type CountOTPsCreatedSinceParams struct {
	Target    string             `json:"target"`
	Purpose   string             `json:"purpose"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountOTPsCreatedSince(ctx context.Context, arg CountOTPsCreatedSinceParams) (int32, error) {
	row := q.db.QueryRow(ctx, countOTPsCreatedSince, arg.Target, arg.Purpose, arg.CreatedAt)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createOTP = `-- name: CreateOTP :one
INSERT INTO otps (
    target,
    otp_code,
    purpose,
    max_attempt,
    expires_at
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, target, otp_code, purpose, attempt_count, max_attempt, expires_at, used_at, status, metadata, created_at, updated_at, deleted_at
`

type CreateOTPParams struct {
	Target     string             `json:"target"`
	OtpCode    string             `json:"otp_code"`
	Purpose    string             `json:"purpose"`
	MaxAttempt pgtype.Int4        `json:"max_attempt"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateOTP(ctx context.Context, arg CreateOTPParams) (Otp, error) {
	row := q.db.QueryRow(ctx, createOTP,
		arg.Target,
		arg.OtpCode,
		arg.Purpose,
		arg.MaxAttempt,
		arg.ExpiresAt,
	)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.OtpCode,
		&i.Purpose,
		&i.AttemptCount,
		&i.MaxAttempt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const expireOldOTPs = `-- name: ExpireOldOTPs :exec
UPDATE otps
SET status = 'expired',
    updated_at = now()
WHERE expires_at < now()
  AND status = 'active'
`

func (q *Queries) ExpireOldOTPs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, expireOldOTPs)
	return err
}

const getActiveOTP = `-- name: GetActiveOTP :one
SELECT id, target, otp_code, purpose, attempt_count, max_attempt, expires_at, used_at, status, metadata, created_at, updated_at, deleted_at FROM otps
WHERE target = $1 
  AND purpose = $2 
  AND status = 'active'
  AND expires_at > now()
ORDER BY created_at DESC
LIMIT 1
`

type GetActiveOTPParams struct {
	Target  string `json:"target"`
	Purpose string `json:"purpose"`
}

func (q *Queries) GetActiveOTP(ctx context.Context, arg GetActiveOTPParams) (Otp, error) {
	row := q.db.QueryRow(ctx, getActiveOTP, arg.Target, arg.Purpose)
	var i Otp
	err := row.Scan(
		&i.ID,
		&i.Target,
		&i.OtpCode,
		&i.Purpose,
		&i.AttemptCount,
		&i.MaxAttempt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.Status,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLastOTPCreatedAt = `-- name: GetLastOTPCreatedAt :one
SELECT created_at FROM otps
WHERE target = $1 AND purpose = $2
ORDER BY created_at DESC
LIMIT 1
`

type GetLastOTPCreatedAtParams struct {
	Target  string `json:"target"`
	Purpose string `json:"purpose"`
}

func (q *Queries) GetLastOTPCreatedAt(ctx context.Context, arg GetLastOTPCreatedAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastOTPCreatedAt, arg.Target, arg.Purpose)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const getOldestOTPCreatedAtSince = `-- name: GetOldestOTPCreatedAtSince :one
SELECT created_at FROM otps
WHERE target = $1 AND purpose = $2 AND created_at >= $3
ORDER BY created_at ASC
LIMIT 1
`

type GetOldestOTPCreatedAtSinceParams struct {
	Target    string             `json:"target"`
	Purpose   string             `json:"purpose"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetOldestOTPCreatedAtSince(ctx context.Context, arg GetOldestOTPCreatedAtSinceParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getOldestOTPCreatedAtSince, arg.Target, arg.Purpose, arg.CreatedAt)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const incrementOTPAttempt = `-- name: IncrementOTPAttempt :exec
UPDATE otps
SET attempt_count = attempt_count + 1,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) IncrementOTPAttempt(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementOTPAttempt, id)
	return err
}

const lockOTP = `-- name: LockOTP :exec
UPDATE otps
SET status = 'locked',
    updated_at = now()
WHERE id = $1
`

func (q *Queries) LockOTP(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, lockOTP, id)
	return err
}

const lockOTPWithCount = `-- name: LockOTPWithCount :exec
UPDATE otps
SET status = 'locked',
    attempt_count = $2,
    updated_at = now()
WHERE id = $1
`

type LockOTPWithCountParams struct {
	ID           uuid.UUID   `json:"id"`
	AttemptCount pgtype.Int4 `json:"attempt_count"`
}

func (q *Queries) LockOTPWithCount(ctx context.Context, arg LockOTPWithCountParams) error {
	_, err := q.db.Exec(ctx, lockOTPWithCount, arg.ID, arg.AttemptCount)
	return err
}

const markOTPAsUsed = `-- name: MarkOTPAsUsed :exec
UPDATE otps
SET status = 'used',
    used_at = now(),
    updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkOTPAsUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markOTPAsUsed, id)
	return err
}

const markOTPAsUsedWithCount = `-- name: MarkOTPAsUsedWithCount :exec
UPDATE otps
SET status = 'used',
    used_at = now(),
    attempt_count = $2,
    updated_at = now()
WHERE id = $1
`

type MarkOTPAsUsedWithCountParams struct {
	ID           uuid.UUID   `json:"id"`
	AttemptCount pgtype.Int4 `json:"attempt_count"`
}

func (q *Queries) MarkOTPAsUsedWithCount(ctx context.Context, arg MarkOTPAsUsedWithCountParams) error {
	_, err := q.db.Exec(ctx, markOTPAsUsedWithCount, arg.ID, arg.AttemptCount)
	return err
}
