// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otp_audit.sql

package pgdb

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createOTPAudit = `-- name: CreateOTPAudit :one
INSERT INTO system_otp_audits (
    otp_id,
    target,
    purpose,
    attempt_number,
    result,
    failure_reason,
    ip_address,
    user_agent,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
) RETURNING id, otp_id, target, purpose, attempt_number, result, failure_reason, ip_address, user_agent, metadata, created_at, updated_at, deleted_at
`

type CreateOTPAuditParams struct {
	OtpID         uuid.UUID   `json:"otp_id"`
	Target        string      `json:"target"`
	Purpose       string      `json:"purpose"`
	AttemptNumber int32       `json:"attempt_number"`
	Result        string      `json:"result"`
	FailureReason pgtype.Text `json:"failure_reason"`
	IpAddress     *netip.Addr `json:"ip_address"`
	UserAgent     pgtype.Text `json:"user_agent"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) CreateOTPAudit(ctx context.Context, arg CreateOTPAuditParams) (SystemOtpAudit, error) {
	row := q.db.QueryRow(ctx, createOTPAudit,
		arg.OtpID,
		arg.Target,
		arg.Purpose,
		arg.AttemptNumber,
		arg.Result,
		arg.FailureReason,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
	)
	var i SystemOtpAudit
	err := row.Scan(
		&i.ID,
		&i.OtpID,
		&i.Target,
		&i.Purpose,
		&i.AttemptNumber,
		&i.Result,
		&i.FailureReason,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
