// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: package_size_pricing.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPackageSizePricing = `-- name: CreatePackageSizePricing :one
INSERT INTO system_package_size_pricing (service_id, package_size, extra_price, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, service_id, package_size, extra_price, is_active, created_at, updated_at, deleted_at
`

type CreatePackageSizePricingParams struct {
	ServiceID   uuid.UUID      `json:"service_id"`
	PackageSize string         `json:"package_size"`
	ExtraPrice  pgtype.Numeric `json:"extra_price"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) CreatePackageSizePricing(ctx context.Context, arg CreatePackageSizePricingParams) (SystemPackageSizePricing, error) {
	row := q.db.QueryRow(ctx, createPackageSizePricing,
		arg.ServiceID,
		arg.PackageSize,
		arg.ExtraPrice,
		arg.IsActive,
	)
	var i SystemPackageSizePricing
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.PackageSize,
		&i.ExtraPrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deletePackageSizePricing = `-- name: DeletePackageSizePricing :exec
UPDATE system_package_size_pricing
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeletePackageSizePricing(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePackageSizePricing, id)
	return err
}

const getPackageSizePricingByID = `-- name: GetPackageSizePricingByID :one
SELECT id, service_id, package_size, extra_price, is_active, created_at, updated_at, deleted_at FROM system_package_size_pricing
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetPackageSizePricingByID(ctx context.Context, id uuid.UUID) (SystemPackageSizePricing, error) {
	row := q.db.QueryRow(ctx, getPackageSizePricingByID, id)
	var i SystemPackageSizePricing
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.PackageSize,
		&i.ExtraPrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPackageSizePricings = `-- name: ListPackageSizePricings :many
SELECT id, service_id, package_size, extra_price, is_active, created_at, updated_at, deleted_at FROM system_package_size_pricing
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR service_id = $1::uuid)
ORDER BY service_id ASC, package_size ASC, created_at DESC
`

func (q *Queries) ListPackageSizePricings(ctx context.Context, serviceID pgtype.UUID) ([]SystemPackageSizePricing, error) {
	rows, err := q.db.Query(ctx, listPackageSizePricings, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemPackageSizePricing{}
	for rows.Next() {
		var i SystemPackageSizePricing
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.PackageSize,
			&i.ExtraPrice,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePackageSizePricing = `-- name: UpdatePackageSizePricing :one
UPDATE system_package_size_pricing
SET
  service_id = $2,
  package_size = $3,
  extra_price = $4,
  is_active = $5,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, service_id, package_size, extra_price, is_active, created_at, updated_at, deleted_at
`

type UpdatePackageSizePricingParams struct {
	ID          uuid.UUID      `json:"id"`
	ServiceID   uuid.UUID      `json:"service_id"`
	PackageSize string         `json:"package_size"`
	ExtraPrice  pgtype.Numeric `json:"extra_price"`
	IsActive    bool           `json:"is_active"`
}

func (q *Queries) UpdatePackageSizePricing(ctx context.Context, arg UpdatePackageSizePricingParams) (SystemPackageSizePricing, error) {
	row := q.db.QueryRow(ctx, updatePackageSizePricing,
		arg.ID,
		arg.ServiceID,
		arg.PackageSize,
		arg.ExtraPrice,
		arg.IsActive,
	)
	var i SystemPackageSizePricing
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.PackageSize,
		&i.ExtraPrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
