// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: permissions.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPermissions = `-- name: CountPermissions :one
SELECT COUNT(*) FROM system_permissions
WHERE ($1::text = '' OR resource ILIKE '%' || $1 || '%' OR action ILIKE '%' || $1 || '%' OR name ILIKE '%' || $1 || '%')
`

func (q *Queries) CountPermissions(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countPermissions, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPermission = `-- name: CreatePermission :one
INSERT INTO system_permissions (resource, action, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, resource, action, code, name, description, created_at, updated_at
`

type CreatePermissionParams struct {
	Resource    string `json:"resource"`
	Action      string `json:"action"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreatePermission(ctx context.Context, arg CreatePermissionParams) (SystemPermission, error) {
	row := q.db.QueryRow(ctx, createPermission,
		arg.Resource,
		arg.Action,
		arg.Name,
		arg.Description,
	)
	var i SystemPermission
	err := row.Scan(
		&i.ID,
		&i.Resource,
		&i.Action,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePermission = `-- name: DeletePermission :exec
DELETE FROM system_permissions
WHERE id = $1
`

func (q *Queries) DeletePermission(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePermission, id)
	return err
}

const getPermissionByCode = `-- name: GetPermissionByCode :one
SELECT id, resource, action, code, name, description, created_at, updated_at FROM system_permissions
WHERE code = $1
`

func (q *Queries) GetPermissionByCode(ctx context.Context, code pgtype.Text) (SystemPermission, error) {
	row := q.db.QueryRow(ctx, getPermissionByCode, code)
	var i SystemPermission
	err := row.Scan(
		&i.ID,
		&i.Resource,
		&i.Action,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPermissionByID = `-- name: GetPermissionByID :one
SELECT id, resource, action, code, name, description, created_at, updated_at FROM system_permissions
WHERE id = $1
`

func (q *Queries) GetPermissionByID(ctx context.Context, id uuid.UUID) (SystemPermission, error) {
	row := q.db.QueryRow(ctx, getPermissionByID, id)
	var i SystemPermission
	err := row.Scan(
		&i.ID,
		&i.Resource,
		&i.Action,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPermissionsByIDs = `-- name: GetPermissionsByIDs :many
SELECT id, resource, action, code, name, description, created_at, updated_at FROM system_permissions
WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetPermissionsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]SystemPermission, error) {
	rows, err := q.db.Query(ctx, getPermissionsByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemPermission{}
	for rows.Next() {
		var i SystemPermission
		if err := rows.Scan(
			&i.ID,
			&i.Resource,
			&i.Action,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, resource, action, code, name, description, created_at, updated_at FROM system_permissions
WHERE ($1::text = '' OR resource ILIKE '%' || $1 || '%' OR action ILIKE '%' || $1 || '%' OR name ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPermissionsParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]SystemPermission, error) {
	rows, err := q.db.Query(ctx, listPermissions, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemPermission{}
	for rows.Next() {
		var i SystemPermission
		if err := rows.Scan(
			&i.ID,
			&i.Resource,
			&i.Action,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePermission = `-- name: UpdatePermission :one
UPDATE system_permissions
SET
    resource = $2,
    action = $3,
    name = $4,
    description = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, resource, action, code, name, description, created_at, updated_at
`

type UpdatePermissionParams struct {
	ID          uuid.UUID `json:"id"`
	Resource    string    `json:"resource"`
	Action      string    `json:"action"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
}

func (q *Queries) UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (SystemPermission, error) {
	row := q.db.QueryRow(ctx, updatePermission,
		arg.ID,
		arg.Resource,
		arg.Action,
		arg.Name,
		arg.Description,
	)
	var i SystemPermission
	err := row.Scan(
		&i.ID,
		&i.Resource,
		&i.Action,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
