// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountAccounts(ctx context.Context) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateOTP(ctx context.Context, arg CreateOTPParams) (Otp, error)
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error)
	DeleteAccount(ctx context.Context, id uuid.UUID) error
	ExpireOldOTPs(ctx context.Context) error
	GetAccountByEmail(ctx context.Context, email pgtype.Text) (Account, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountByPhone(ctx context.Context, phone string) (Account, error)
	GetActiveOTP(ctx context.Context, arg GetActiveOTPParams) (Otp, error)
	GetUserProfileByAccountId(ctx context.Context, accountID uuid.UUID) (UserProfile, error)
	IncrementOTPAttempt(ctx context.Context, id uuid.UUID) error
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	LockOTP(ctx context.Context, id uuid.UUID) error
	LockOTPWithCount(ctx context.Context, arg LockOTPWithCountParams) error
	MarkOTPAsUsed(ctx context.Context, id uuid.UUID) error
	MarkOTPAsUsedWithCount(ctx context.Context, arg MarkOTPAsUsedWithCountParams) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error)
}

var _ Querier = (*Queries)(nil)
