// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddSurchargeRuleConditions(ctx context.Context, arg AddSurchargeRuleConditionsParams) error
	CountAccounts(ctx context.Context) (int64, error)
	CountDriverDocumentTypes(ctx context.Context, dollar_1 interface{}) (int64, error)
	CountDriverDocumentTypesByServiceID(ctx context.Context, arg CountDriverDocumentTypesByServiceIDParams) (int64, error)
	CountOTPsCreatedSince(ctx context.Context, arg CountOTPsCreatedSinceParams) (int32, error)
	CountPermissions(ctx context.Context, dollar_1 string) (int64, error)
	CountRoles(ctx context.Context, dollar_1 string) (int64, error)
	CountServices(ctx context.Context, dollar_1 interface{}) (int64, error)
	CountSidebars(ctx context.Context, dollar_1 interface{}) (int64, error)
	CountSystemAdmins(ctx context.Context, dollar_1 string) (int64, error)
	CountZones(ctx context.Context, dollar_1 interface{}) (int64, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error)
	CreateAccountAppDevice(ctx context.Context, arg CreateAccountAppDeviceParams) (AccountAppDevice, error)
	CreateDevice(ctx context.Context, arg CreateDeviceParams) (Device, error)
	CreateDistancePricingRule(ctx context.Context, arg CreateDistancePricingRuleParams) (SystemDistancePricingRule, error)
	CreateDriverDocument(ctx context.Context, arg CreateDriverDocumentParams) (DriverDocument, error)
	CreateDriverDocumentType(ctx context.Context, arg CreateDriverDocumentTypeParams) (DriverDocumentType, error)
	CreateDriverProfile(ctx context.Context, arg CreateDriverProfileParams) (DriverProfile, error)
	CreateDriverProfileStatusHistory(ctx context.Context, arg CreateDriverProfileStatusHistoryParams) (DriverProfileStatusHistory, error)
	CreateLoginHistory(ctx context.Context, arg CreateLoginHistoryParams) (AppLoginHistory, error)
	CreateOTP(ctx context.Context, arg CreateOTPParams) (SystemOtp, error)
	CreateOTPAudit(ctx context.Context, arg CreateOTPAuditParams) (SystemOtpAudit, error)
	CreatePackageSizePricing(ctx context.Context, arg CreatePackageSizePricingParams) (SystemPackageSizePricing, error)
	CreatePermission(ctx context.Context, arg CreatePermissionParams) (SystemPermission, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (SystemRole, error)
	CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) error
	CreateRolePermissionsBatch(ctx context.Context, arg CreateRolePermissionsBatchParams) error
	CreateService(ctx context.Context, arg CreateServiceParams) (SystemService, error)
	CreateServiceZone(ctx context.Context, arg CreateServiceZoneParams) (SystemServiceZone, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (SystemSession, error)
	CreateSidebar(ctx context.Context, arg CreateSidebarParams) (SystemSidebar, error)
	CreateSurchargeCondition(ctx context.Context, arg CreateSurchargeConditionParams) (SystemSurchargeCondition, error)
	CreateSurchargeRule(ctx context.Context, arg CreateSurchargeRuleParams) (SystemSurchargeRule, error)
	CreateSystemAdmin(ctx context.Context, arg CreateSystemAdminParams) (SystemAdmin, error)
	CreateSystemAdminRefreshToken(ctx context.Context, arg CreateSystemAdminRefreshTokenParams) (SystemAdminRefreshToken, error)
	CreateSystemLoginHistory(ctx context.Context, arg CreateSystemLoginHistoryParams) (SystemLoginHistory, error)
	CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error)
	CreateZone(ctx context.Context, arg CreateZoneParams) (SystemZone, error)
	DeleteAccount(ctx context.Context, id uuid.UUID) error
	DeleteAccountAppDevice(ctx context.Context, id uuid.UUID) error
	DeleteAdminRolesByAdminID(ctx context.Context, adminID uuid.UUID) error
	DeleteDevice(ctx context.Context, id uuid.UUID) error
	DeleteDistancePricingRule(ctx context.Context, id uuid.UUID) error
	DeleteDriverDocument(ctx context.Context, id uuid.UUID) error
	DeleteDriverDocumentType(ctx context.Context, id uuid.UUID) error
	DeleteExpiredSessions(ctx context.Context) error
	DeletePackageSizePricing(ctx context.Context, id uuid.UUID) error
	DeletePermission(ctx context.Context, id uuid.UUID) error
	DeleteRole(ctx context.Context, id uuid.UUID) error
	DeleteRolePermissionsByRoleID(ctx context.Context, roleID uuid.UUID) error
	DeleteService(ctx context.Context, id uuid.UUID) error
	DeleteServiceZonesByServiceID(ctx context.Context, serviceID uuid.UUID) error
	DeleteSidebar(ctx context.Context, id uuid.UUID) error
	DeleteSurchargeCondition(ctx context.Context, id uuid.UUID) error
	DeleteSurchargeRule(ctx context.Context, id uuid.UUID) error
	DeleteSurchargeRuleConditionsBySurchargeID(ctx context.Context, surchargeID uuid.UUID) error
	DeleteSystemAdmin(ctx context.Context, id uuid.UUID) error
	DeleteZone(ctx context.Context, id uuid.UUID) error
	ExpireOldOTPs(ctx context.Context) error
	GetAccountAppDevice(ctx context.Context, arg GetAccountAppDeviceParams) (AccountAppDevice, error)
	GetAccountAppDeviceByID(ctx context.Context, id uuid.UUID) (AccountAppDevice, error)
	GetAccountByEmail(ctx context.Context, email pgtype.Text) (Account, error)
	GetAccountByID(ctx context.Context, id uuid.UUID) (Account, error)
	GetAccountByPhone(ctx context.Context, phone string) (Account, error)
	GetActiveOTP(ctx context.Context, arg GetActiveOTPParams) (SystemOtp, error)
	GetConditionIDsBySurchargeID(ctx context.Context, surchargeID uuid.UUID) ([]uuid.UUID, error)
	GetDeviceByID(ctx context.Context, id uuid.UUID) (Device, error)
	GetDeviceByUID(ctx context.Context, deviceUid string) (Device, error)
	GetDistancePricingRuleByID(ctx context.Context, id uuid.UUID) (SystemDistancePricingRule, error)
	GetDriverDocumentByID(ctx context.Context, id uuid.UUID) (DriverDocument, error)
	GetDriverDocumentTypeByCodeAndServiceID(ctx context.Context, arg GetDriverDocumentTypeByCodeAndServiceIDParams) (DriverDocumentType, error)
	GetDriverDocumentTypeByCodeGlobal(ctx context.Context, code string) (DriverDocumentType, error)
	GetDriverDocumentTypeByID(ctx context.Context, id uuid.UUID) (DriverDocumentType, error)
	GetDriverProfileByAccountID(ctx context.Context, accountID uuid.UUID) (DriverProfile, error)
	GetDriverProfileByID(ctx context.Context, id uuid.UUID) (DriverProfile, error)
	GetLastOTPCreatedAt(ctx context.Context, arg GetLastOTPCreatedAtParams) (pgtype.Timestamptz, error)
	GetOldestOTPCreatedAtSince(ctx context.Context, arg GetOldestOTPCreatedAtSinceParams) (pgtype.Timestamptz, error)
	GetPackageSizePricingByID(ctx context.Context, id uuid.UUID) (SystemPackageSizePricing, error)
	GetPermissionByCode(ctx context.Context, code pgtype.Text) (SystemPermission, error)
	GetPermissionByID(ctx context.Context, id uuid.UUID) (SystemPermission, error)
	GetPermissionIDsByRoleID(ctx context.Context, roleID uuid.UUID) ([]uuid.UUID, error)
	GetPermissionsByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]SystemPermission, error)
	GetRoleByCode(ctx context.Context, code string) (SystemRole, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (SystemRole, error)
	GetRoleIDsByAdminID(ctx context.Context, adminID uuid.UUID) ([]uuid.UUID, error)
	GetRolePermissionPairsByRoleIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]SystemRolePermission, error)
	GetRolesByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]SystemRole, error)
	GetServiceByCode(ctx context.Context, code string) (SystemService, error)
	GetServiceByID(ctx context.Context, id uuid.UUID) (SystemService, error)
	GetSessionByID(ctx context.Context, id uuid.UUID) (SystemSession, error)
	GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (SystemSession, error)
	GetSettingByKey(ctx context.Context, key string) (SystemSetting, error)
	GetSidebarByContext(ctx context.Context, argContext string) (SystemSidebar, error)
	GetSidebarByID(ctx context.Context, id uuid.UUID) (SystemSidebar, error)
	GetSurchargeConditionByCode(ctx context.Context, code string) (SystemSurchargeCondition, error)
	GetSurchargeConditionByID(ctx context.Context, id uuid.UUID) (SystemSurchargeCondition, error)
	GetSurchargeRuleByID(ctx context.Context, id uuid.UUID) (SystemSurchargeRule, error)
	GetSystemAdminByEmail(ctx context.Context, email string) (SystemAdmin, error)
	GetSystemAdminByID(ctx context.Context, id uuid.UUID) (SystemAdmin, error)
	GetSystemAdminRefreshTokenByHash(ctx context.Context, refreshTokenHash string) (SystemAdminRefreshToken, error)
	GetUserProfileByAccountId(ctx context.Context, accountID uuid.UUID) (UserProfile, error)
	GetUserProfileByID(ctx context.Context, id uuid.UUID) (UserProfile, error)
	GetZoneByCode(ctx context.Context, code string) (GetZoneByCodeRow, error)
	GetZoneByID(ctx context.Context, id uuid.UUID) (GetZoneByIDRow, error)
	IncrementOTPAttempt(ctx context.Context, id uuid.UUID) error
	InsertAdminRole(ctx context.Context, arg InsertAdminRoleParams) error
	ListAccountAppDevices(ctx context.Context, accountID uuid.UUID) ([]AccountAppDevice, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Account, error)
	ListActiveSessions(ctx context.Context, accountID uuid.UUID) ([]ListActiveSessionsRow, error)
	ListDistancePricingRules(ctx context.Context, serviceID pgtype.UUID) ([]SystemDistancePricingRule, error)
	ListDistancePricingRulesByServiceID(ctx context.Context, serviceID uuid.UUID) ([]SystemDistancePricingRule, error)
	ListDriverDocumentTypes(ctx context.Context, arg ListDriverDocumentTypesParams) ([]DriverDocumentType, error)
	ListDriverDocumentTypesByServiceID(ctx context.Context, arg ListDriverDocumentTypesByServiceIDParams) ([]DriverDocumentType, error)
	ListDriverDocumentsByDriverID(ctx context.Context, driverID uuid.UUID) ([]DriverDocument, error)
	ListPackageSizePricings(ctx context.Context, serviceID pgtype.UUID) ([]SystemPackageSizePricing, error)
	ListPermissions(ctx context.Context, arg ListPermissionsParams) ([]SystemPermission, error)
	// Trả về document types áp dụng cho service: theo service_id HOẶC chung (service_id IS NULL).
	ListRequiredDriverDocumentTypesByServiceID(ctx context.Context, serviceID *uuid.UUID) ([]DriverDocumentType, error)
	ListRoles(ctx context.Context, arg ListRolesParams) ([]SystemRole, error)
	ListServiceZonesByServiceID(ctx context.Context, serviceID uuid.UUID) ([]SystemServiceZone, error)
	ListServices(ctx context.Context, arg ListServicesParams) ([]SystemService, error)
	ListSidebars(ctx context.Context, arg ListSidebarsParams) ([]SystemSidebar, error)
	ListSurchargeConditions(ctx context.Context) ([]SystemSurchargeCondition, error)
	ListSurchargeRules(ctx context.Context, arg ListSurchargeRulesParams) ([]SystemSurchargeRule, error)
	ListSystemAdmins(ctx context.Context, arg ListSystemAdminsParams) ([]SystemAdmin, error)
	ListZones(ctx context.Context, arg ListZonesParams) ([]ListZonesRow, error)
	LockOTP(ctx context.Context, id uuid.UUID) error
	LockOTPWithCount(ctx context.Context, arg LockOTPWithCountParams) error
	MarkOTPAsUsed(ctx context.Context, id uuid.UUID) error
	MarkOTPAsUsedWithCount(ctx context.Context, arg MarkOTPAsUsedWithCountParams) error
	RevokeAllSessionsByAccount(ctx context.Context, arg RevokeAllSessionsByAccountParams) error
	RevokeAllSessionsByAccountAppDevice(ctx context.Context, arg RevokeAllSessionsByAccountAppDeviceParams) error
	RevokeAllSystemAdminRefreshTokens(ctx context.Context, arg RevokeAllSystemAdminRefreshTokensParams) error
	RevokeSession(ctx context.Context, arg RevokeSessionParams) error
	RevokeSessionByRefreshToken(ctx context.Context, arg RevokeSessionByRefreshTokenParams) error
	RevokeSystemAdminRefreshTokenByHash(ctx context.Context, arg RevokeSystemAdminRefreshTokenByHashParams) error
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Account, error)
	UpdateAccountAppDevice(ctx context.Context, arg UpdateAccountAppDeviceParams) (AccountAppDevice, error)
	UpdateDevice(ctx context.Context, arg UpdateDeviceParams) (Device, error)
	UpdateDistancePricingRule(ctx context.Context, arg UpdateDistancePricingRuleParams) (SystemDistancePricingRule, error)
	UpdateDriverDocument(ctx context.Context, arg UpdateDriverDocumentParams) (DriverDocument, error)
	// Bulk update (PATCH): chỉ cập nhật các field được truyền (khác NULL).
	UpdateDriverDocumentPartial(ctx context.Context, arg UpdateDriverDocumentPartialParams) (DriverDocument, error)
	UpdateDriverDocumentType(ctx context.Context, arg UpdateDriverDocumentTypeParams) (DriverDocumentType, error)
	UpdateDriverProfile(ctx context.Context, arg UpdateDriverProfileParams) (DriverProfile, error)
	UpdatePackageSizePricing(ctx context.Context, arg UpdatePackageSizePricingParams) (SystemPackageSizePricing, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) error
	UpdatePermission(ctx context.Context, arg UpdatePermissionParams) (SystemPermission, error)
	UpdateRole(ctx context.Context, arg UpdateRoleParams) (SystemRole, error)
	UpdateService(ctx context.Context, arg UpdateServiceParams) (SystemService, error)
	UpdateSessionActivity(ctx context.Context, id uuid.UUID) error
	UpdateSidebar(ctx context.Context, arg UpdateSidebarParams) (SystemSidebar, error)
	UpdateSurchargeCondition(ctx context.Context, arg UpdateSurchargeConditionParams) (SystemSurchargeCondition, error)
	UpdateSurchargeRule(ctx context.Context, arg UpdateSurchargeRuleParams) (SystemSurchargeRule, error)
	UpdateSystemAdmin(ctx context.Context, arg UpdateSystemAdminParams) (SystemAdmin, error)
	UpdateSystemAdminLastLoginAt(ctx context.Context, arg UpdateSystemAdminLastLoginAtParams) error
	UpdateSystemAdminRefreshTokenActivity(ctx context.Context, id uuid.UUID) error
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error)
	UpdateZone(ctx context.Context, arg UpdateZoneParams) (SystemZone, error)
}

var _ Querier = (*Queries)(nil)
