// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: role_permissions.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
)

const createRolePermission = `-- name: CreateRolePermission :exec
INSERT INTO system_role_permissions (role_id, permission_id)
VALUES ($1, $2)
`

type CreateRolePermissionParams struct {
	RoleID       uuid.UUID `json:"role_id"`
	PermissionID uuid.UUID `json:"permission_id"`
}

func (q *Queries) CreateRolePermission(ctx context.Context, arg CreateRolePermissionParams) error {
	_, err := q.db.Exec(ctx, createRolePermission, arg.RoleID, arg.PermissionID)
	return err
}

const createRolePermissionsBatch = `-- name: CreateRolePermissionsBatch :exec
INSERT INTO system_role_permissions (role_id, permission_id)
SELECT $1, unnest($2::uuid[])
`

type CreateRolePermissionsBatchParams struct {
	RoleID  uuid.UUID   `json:"role_id"`
	Column2 []uuid.UUID `json:"column_2"`
}

func (q *Queries) CreateRolePermissionsBatch(ctx context.Context, arg CreateRolePermissionsBatchParams) error {
	_, err := q.db.Exec(ctx, createRolePermissionsBatch, arg.RoleID, arg.Column2)
	return err
}

const deleteRolePermissionsByRoleID = `-- name: DeleteRolePermissionsByRoleID :exec
DELETE FROM system_role_permissions
WHERE role_id = $1
`

func (q *Queries) DeleteRolePermissionsByRoleID(ctx context.Context, roleID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRolePermissionsByRoleID, roleID)
	return err
}

const getPermissionIDsByRoleID = `-- name: GetPermissionIDsByRoleID :many
SELECT permission_id FROM system_role_permissions
WHERE role_id = $1
`

func (q *Queries) GetPermissionIDsByRoleID(ctx context.Context, roleID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getPermissionIDsByRoleID, roleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var permission_id uuid.UUID
		if err := rows.Scan(&permission_id); err != nil {
			return nil, err
		}
		items = append(items, permission_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRolePermissionPairsByRoleIDs = `-- name: GetRolePermissionPairsByRoleIDs :many
SELECT role_id, permission_id FROM system_role_permissions
WHERE role_id = ANY($1::uuid[])
`

func (q *Queries) GetRolePermissionPairsByRoleIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]SystemRolePermission, error) {
	rows, err := q.db.Query(ctx, getRolePermissionPairsByRoleIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemRolePermission{}
	for rows.Next() {
		var i SystemRolePermission
		if err := rows.Scan(&i.RoleID, &i.PermissionID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
