// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: roles.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
)

const countRoles = `-- name: CountRoles :one
SELECT COUNT(*) FROM system_roles
WHERE ($1::text = '' OR code ILIKE '%' || $1 || '%' OR name ILIKE '%' || $1 || '%')
`

func (q *Queries) CountRoles(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRow(ctx, countRoles, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO system_roles (code, name, description, is_active)
VALUES ($1, $2, $3, $4)
RETURNING id, code, name, description, is_active, created_at, updated_at, deleted_at
`

type CreateRoleParams struct {
	Code        string `json:"code"`
	Name        string `json:"name"`
	Description string `json:"description"`
	IsActive    bool   `json:"is_active"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (SystemRole, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.IsActive,
	)
	var i SystemRole
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteRole = `-- name: DeleteRole :exec
DELETE FROM system_roles
WHERE id = $1
`

func (q *Queries) DeleteRole(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRole, id)
	return err
}

const getRoleByCode = `-- name: GetRoleByCode :one
SELECT id, code, name, description, is_active, created_at, updated_at, deleted_at FROM system_roles
WHERE code = $1
`

func (q *Queries) GetRoleByCode(ctx context.Context, code string) (SystemRole, error) {
	row := q.db.QueryRow(ctx, getRoleByCode, code)
	var i SystemRole
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRoleByID = `-- name: GetRoleByID :one
SELECT id, code, name, description, is_active, created_at, updated_at, deleted_at FROM system_roles
WHERE id = $1
`

func (q *Queries) GetRoleByID(ctx context.Context, id uuid.UUID) (SystemRole, error) {
	row := q.db.QueryRow(ctx, getRoleByID, id)
	var i SystemRole
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRolesByIDs = `-- name: GetRolesByIDs :many
SELECT id, code, name, description, is_active, created_at, updated_at, deleted_at FROM system_roles
WHERE id = ANY($1::uuid[])
`

func (q *Queries) GetRolesByIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]SystemRole, error) {
	rows, err := q.db.Query(ctx, getRolesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemRole{}
	for rows.Next() {
		var i SystemRole
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRoles = `-- name: ListRoles :many
SELECT id, code, name, description, is_active, created_at, updated_at, deleted_at FROM system_roles
WHERE ($1::text = '' OR code ILIKE '%' || $1 || '%' OR name ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListRolesParams struct {
	Column1 string `json:"column_1"`
	Limit   int32  `json:"limit"`
	Offset  int32  `json:"offset"`
}

func (q *Queries) ListRoles(ctx context.Context, arg ListRolesParams) ([]SystemRole, error) {
	rows, err := q.db.Query(ctx, listRoles, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemRole{}
	for rows.Next() {
		var i SystemRole
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRole = `-- name: UpdateRole :one
UPDATE system_roles
SET
    code = $2,
    name = $3,
    description = $4,
    is_active = $5,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, code, name, description, is_active, created_at, updated_at, deleted_at
`

type UpdateRoleParams struct {
	ID          uuid.UUID `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsActive    bool      `json:"is_active"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (SystemRole, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.Description,
		arg.IsActive,
	)
	var i SystemRole
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
