// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countServices = `-- name: CountServices :one
SELECT COUNT(*) FROM system_services
WHERE deleted_at IS NULL
  AND ($1 = '' OR name ILIKE '%' || $1 || '%' OR code ILIKE '%' || $1 || '%')
`

func (q *Queries) CountServices(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countServices, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createService = `-- name: CreateService :one
INSERT INTO system_services (
  code,
  name,
  base_price,
  min_price,
  is_active
)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, name, base_price, min_price, is_active, created_at, updated_at, deleted_at
`

type CreateServiceParams struct {
	Code      string         `json:"code"`
	Name      string         `json:"name"`
	BasePrice pgtype.Numeric `json:"base_price"`
	MinPrice  pgtype.Numeric `json:"min_price"`
	IsActive  bool           `json:"is_active"`
}

func (q *Queries) CreateService(ctx context.Context, arg CreateServiceParams) (SystemService, error) {
	row := q.db.QueryRow(ctx, createService,
		arg.Code,
		arg.Name,
		arg.BasePrice,
		arg.MinPrice,
		arg.IsActive,
	)
	var i SystemService
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.BasePrice,
		&i.MinPrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteService = `-- name: DeleteService :exec
UPDATE system_services
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteService(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteService, id)
	return err
}

const getServiceByCode = `-- name: GetServiceByCode :one
SELECT id, code, name, base_price, min_price, is_active, created_at, updated_at, deleted_at FROM system_services
WHERE code = $1 AND deleted_at IS NULL
`

func (q *Queries) GetServiceByCode(ctx context.Context, code string) (SystemService, error) {
	row := q.db.QueryRow(ctx, getServiceByCode, code)
	var i SystemService
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.BasePrice,
		&i.MinPrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getServiceByID = `-- name: GetServiceByID :one
SELECT id, code, name, base_price, min_price, is_active, created_at, updated_at, deleted_at FROM system_services
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetServiceByID(ctx context.Context, id uuid.UUID) (SystemService, error) {
	row := q.db.QueryRow(ctx, getServiceByID, id)
	var i SystemService
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.BasePrice,
		&i.MinPrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listServices = `-- name: ListServices :many
SELECT id, code, name, base_price, min_price, is_active, created_at, updated_at, deleted_at FROM system_services
WHERE deleted_at IS NULL
  AND ($1 = '' OR name ILIKE '%' || $1 || '%' OR code ILIKE '%' || $1 || '%')
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListServicesParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListServices(ctx context.Context, arg ListServicesParams) ([]SystemService, error) {
	rows, err := q.db.Query(ctx, listServices, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemService{}
	for rows.Next() {
		var i SystemService
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.BasePrice,
			&i.MinPrice,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateService = `-- name: UpdateService :one
UPDATE system_services
SET
  code = $2,
  name = $3,
  base_price = $4,
  min_price = $5,
  is_active = $6,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, code, name, base_price, min_price, is_active, created_at, updated_at, deleted_at
`

type UpdateServiceParams struct {
	ID        uuid.UUID      `json:"id"`
	Code      string         `json:"code"`
	Name      string         `json:"name"`
	BasePrice pgtype.Numeric `json:"base_price"`
	MinPrice  pgtype.Numeric `json:"min_price"`
	IsActive  bool           `json:"is_active"`
}

func (q *Queries) UpdateService(ctx context.Context, arg UpdateServiceParams) (SystemService, error) {
	row := q.db.QueryRow(ctx, updateService,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.BasePrice,
		arg.MinPrice,
		arg.IsActive,
	)
	var i SystemService
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.BasePrice,
		&i.MinPrice,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
