// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: service_zone.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
)

const createServiceZone = `-- name: CreateServiceZone :one
INSERT INTO system_service_zones (zone_id, service_id)
VALUES ($1, $2)
RETURNING id, zone_id, service_id, created_at, updated_at, deleted_at
`

type CreateServiceZoneParams struct {
	ZoneID    uuid.UUID `json:"zone_id"`
	ServiceID uuid.UUID `json:"service_id"`
}

func (q *Queries) CreateServiceZone(ctx context.Context, arg CreateServiceZoneParams) (SystemServiceZone, error) {
	row := q.db.QueryRow(ctx, createServiceZone, arg.ZoneID, arg.ServiceID)
	var i SystemServiceZone
	err := row.Scan(
		&i.ID,
		&i.ZoneID,
		&i.ServiceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteServiceZonesByServiceID = `-- name: DeleteServiceZonesByServiceID :exec
UPDATE system_service_zones
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE service_id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteServiceZonesByServiceID(ctx context.Context, serviceID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteServiceZonesByServiceID, serviceID)
	return err
}

const listServiceZonesByServiceID = `-- name: ListServiceZonesByServiceID :many
SELECT id, zone_id, service_id, created_at, updated_at, deleted_at FROM system_service_zones
WHERE service_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListServiceZonesByServiceID(ctx context.Context, serviceID uuid.UUID) ([]SystemServiceZone, error) {
	rows, err := q.db.Query(ctx, listServiceZonesByServiceID, serviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemServiceZone{}
	for rows.Next() {
		var i SystemServiceZone
		if err := rows.Scan(
			&i.ID,
			&i.ZoneID,
			&i.ServiceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
