// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: session.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO system_sessions (
    account_app_device_id,
    refresh_token_hash,
    expires_at,
    ip_address,
    user_agent,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, account_app_device_id, refresh_token_hash, expires_at, is_revoked, revoked_at, revoked_reason, last_active_at, ip_address, user_agent, metadata, created_at, updated_at, deleted_at
`

type CreateSessionParams struct {
	AccountAppDeviceID uuid.UUID          `json:"account_app_device_id"`
	RefreshTokenHash   string             `json:"refresh_token_hash"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	IpAddress          pgtype.Text        `json:"ip_address"`
	UserAgent          pgtype.Text        `json:"user_agent"`
	Metadata           []byte             `json:"metadata"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (SystemSession, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.AccountAppDeviceID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
	)
	var i SystemSession
	err := row.Scan(
		&i.ID,
		&i.AccountAppDeviceID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.LastActiveAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
UPDATE system_sessions
SET deleted_at = CURRENT_TIMESTAMP
WHERE expires_at < CURRENT_TIMESTAMP
  AND deleted_at IS NULL
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const getSessionByID = `-- name: GetSessionByID :one
SELECT id, account_app_device_id, refresh_token_hash, expires_at, is_revoked, revoked_at, revoked_reason, last_active_at, ip_address, user_agent, metadata, created_at, updated_at, deleted_at FROM system_sessions
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSessionByID(ctx context.Context, id uuid.UUID) (SystemSession, error) {
	row := q.db.QueryRow(ctx, getSessionByID, id)
	var i SystemSession
	err := row.Scan(
		&i.ID,
		&i.AccountAppDeviceID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.LastActiveAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSessionByRefreshTokenHash = `-- name: GetSessionByRefreshTokenHash :one
SELECT id, account_app_device_id, refresh_token_hash, expires_at, is_revoked, revoked_at, revoked_reason, last_active_at, ip_address, user_agent, metadata, created_at, updated_at, deleted_at FROM system_sessions
WHERE refresh_token_hash = $1
  AND is_revoked = false
  AND deleted_at IS NULL
`

func (q *Queries) GetSessionByRefreshTokenHash(ctx context.Context, refreshTokenHash string) (SystemSession, error) {
	row := q.db.QueryRow(ctx, getSessionByRefreshTokenHash, refreshTokenHash)
	var i SystemSession
	err := row.Scan(
		&i.ID,
		&i.AccountAppDeviceID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.LastActiveAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listActiveSessions = `-- name: ListActiveSessions :many
SELECT s.id, s.account_app_device_id, s.refresh_token_hash, s.expires_at, s.is_revoked, s.revoked_at, s.revoked_reason, s.last_active_at, s.ip_address, s.user_agent, s.metadata, s.created_at, s.updated_at, s.deleted_at, aad.account_id, aad.device_id, aad.app_type
FROM system_sessions s
JOIN account_app_devices aad ON s.account_app_device_id = aad.id
WHERE aad.account_id = $1
  AND s.is_revoked = false
  AND s.expires_at > CURRENT_TIMESTAMP
  AND s.deleted_at IS NULL
ORDER BY s.last_active_at DESC
`

type ListActiveSessionsRow struct {
	ID                 uuid.UUID          `json:"id"`
	AccountAppDeviceID uuid.UUID          `json:"account_app_device_id"`
	RefreshTokenHash   string             `json:"refresh_token_hash"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	IsRevoked          bool               `json:"is_revoked"`
	RevokedAt          pgtype.Timestamptz `json:"revoked_at"`
	RevokedReason      pgtype.Text        `json:"revoked_reason"`
	LastActiveAt       pgtype.Timestamptz `json:"last_active_at"`
	IpAddress          pgtype.Text        `json:"ip_address"`
	UserAgent          pgtype.Text        `json:"user_agent"`
	Metadata           []byte             `json:"metadata"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	AccountID          uuid.UUID          `json:"account_id"`
	DeviceID           uuid.UUID          `json:"device_id"`
	AppType            string             `json:"app_type"`
}

func (q *Queries) ListActiveSessions(ctx context.Context, accountID uuid.UUID) ([]ListActiveSessionsRow, error) {
	rows, err := q.db.Query(ctx, listActiveSessions, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveSessionsRow{}
	for rows.Next() {
		var i ListActiveSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountAppDeviceID,
			&i.RefreshTokenHash,
			&i.ExpiresAt,
			&i.IsRevoked,
			&i.RevokedAt,
			&i.RevokedReason,
			&i.LastActiveAt,
			&i.IpAddress,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.AccountID,
			&i.DeviceID,
			&i.AppType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAllSessionsByAccount = `-- name: RevokeAllSessionsByAccount :exec
UPDATE system_sessions
SET
    is_revoked = true,
    revoked_at = CURRENT_TIMESTAMP,
    revoked_reason = $2
WHERE account_app_device_id IN (
    SELECT id FROM account_app_devices WHERE account_id = $1
)
`

type RevokeAllSessionsByAccountParams struct {
	AccountID     uuid.UUID   `json:"account_id"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeAllSessionsByAccount(ctx context.Context, arg RevokeAllSessionsByAccountParams) error {
	_, err := q.db.Exec(ctx, revokeAllSessionsByAccount, arg.AccountID, arg.RevokedReason)
	return err
}

const revokeAllSessionsByAccountAppDevice = `-- name: RevokeAllSessionsByAccountAppDevice :exec
UPDATE system_sessions
SET
    is_revoked = true,
    revoked_at = CURRENT_TIMESTAMP,
    revoked_reason = $2
WHERE account_app_device_id = $1
`

type RevokeAllSessionsByAccountAppDeviceParams struct {
	AccountAppDeviceID uuid.UUID   `json:"account_app_device_id"`
	RevokedReason      pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeAllSessionsByAccountAppDevice(ctx context.Context, arg RevokeAllSessionsByAccountAppDeviceParams) error {
	_, err := q.db.Exec(ctx, revokeAllSessionsByAccountAppDevice, arg.AccountAppDeviceID, arg.RevokedReason)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE system_sessions
SET
    is_revoked = true,
    revoked_at = CURRENT_TIMESTAMP,
    revoked_reason = $2
WHERE id = $1
`

type RevokeSessionParams struct {
	ID            uuid.UUID   `json:"id"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeSession(ctx context.Context, arg RevokeSessionParams) error {
	_, err := q.db.Exec(ctx, revokeSession, arg.ID, arg.RevokedReason)
	return err
}

const revokeSessionByRefreshToken = `-- name: RevokeSessionByRefreshToken :exec
UPDATE system_sessions
SET
    is_revoked = true,
    revoked_at = CURRENT_TIMESTAMP,
    revoked_reason = $2
WHERE refresh_token_hash = $1
`

type RevokeSessionByRefreshTokenParams struct {
	RefreshTokenHash string      `json:"refresh_token_hash"`
	RevokedReason    pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeSessionByRefreshToken(ctx context.Context, arg RevokeSessionByRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, revokeSessionByRefreshToken, arg.RefreshTokenHash, arg.RevokedReason)
	return err
}

const updateSessionActivity = `-- name: UpdateSessionActivity :exec
UPDATE system_sessions
SET last_active_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) UpdateSessionActivity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateSessionActivity, id)
	return err
}
