// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: setting.sql

package pgdb

import (
	"context"
)

const getSettingByKey = `-- name: GetSettingByKey :one
SELECT id, account_id, key, value, type, description, is_active, metadata, created_at, updated_at, deleted_at
FROM settings
WHERE key = $1 AND is_active = true
LIMIT 1
`

func (q *Queries) GetSettingByKey(ctx context.Context, key string) (Setting, error) {
	row := q.db.QueryRow(ctx, getSettingByKey, key)
	var i Setting
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Key,
		&i.Value,
		&i.Type,
		&i.Description,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
