// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sidebar.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSidebars = `-- name: CountSidebars :one
SELECT COUNT(*) FROM system_sidebars
WHERE deleted_at IS NULL
  AND ($1 = '' OR context = $1)
`

func (q *Queries) CountSidebars(ctx context.Context, dollar_1 interface{}) (int64, error) {
	row := q.db.QueryRow(ctx, countSidebars, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSidebar = `-- name: CreateSidebar :one
INSERT INTO system_sidebars (context, version, generated_at, items)
VALUES ($1, $2, $3, $4)
RETURNING id, context, version, generated_at, items, created_at, updated_at, deleted_at
`

type CreateSidebarParams struct {
	Context     string             `json:"context"`
	Version     string             `json:"version"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
	Items       []byte             `json:"items"`
}

func (q *Queries) CreateSidebar(ctx context.Context, arg CreateSidebarParams) (SystemSidebar, error) {
	row := q.db.QueryRow(ctx, createSidebar,
		arg.Context,
		arg.Version,
		arg.GeneratedAt,
		arg.Items,
	)
	var i SystemSidebar
	err := row.Scan(
		&i.ID,
		&i.Context,
		&i.Version,
		&i.GeneratedAt,
		&i.Items,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSidebar = `-- name: DeleteSidebar :exec
UPDATE system_sidebars
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteSidebar(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSidebar, id)
	return err
}

const getSidebarByID = `-- name: GetSidebarByID :one
SELECT id, context, version, generated_at, items, created_at, updated_at, deleted_at
FROM system_sidebars
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSidebarByID(ctx context.Context, id uuid.UUID) (SystemSidebar, error) {
	row := q.db.QueryRow(ctx, getSidebarByID, id)
	var i SystemSidebar
	err := row.Scan(
		&i.ID,
		&i.Context,
		&i.Version,
		&i.GeneratedAt,
		&i.Items,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listSidebars = `-- name: ListSidebars :many
SELECT id, context, version, generated_at, items, created_at, updated_at, deleted_at
FROM system_sidebars
WHERE deleted_at IS NULL
  AND ($1 = '' OR context = $1)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSidebarsParams struct {
	Column1 interface{} `json:"column_1"`
	Limit   int32       `json:"limit"`
	Offset  int32       `json:"offset"`
}

func (q *Queries) ListSidebars(ctx context.Context, arg ListSidebarsParams) ([]SystemSidebar, error) {
	rows, err := q.db.Query(ctx, listSidebars, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSidebar{}
	for rows.Next() {
		var i SystemSidebar
		if err := rows.Scan(
			&i.ID,
			&i.Context,
			&i.Version,
			&i.GeneratedAt,
			&i.Items,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSidebar = `-- name: UpdateSidebar :one
UPDATE system_sidebars
SET
  context = $2,
  version = $3,
  generated_at = $4,
  items = $5,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, context, version, generated_at, items, created_at, updated_at, deleted_at
`

type UpdateSidebarParams struct {
	ID          uuid.UUID          `json:"id"`
	Context     string             `json:"context"`
	Version     string             `json:"version"`
	GeneratedAt pgtype.Timestamptz `json:"generated_at"`
	Items       []byte             `json:"items"`
}

func (q *Queries) UpdateSidebar(ctx context.Context, arg UpdateSidebarParams) (SystemSidebar, error) {
	row := q.db.QueryRow(ctx, updateSidebar,
		arg.ID,
		arg.Context,
		arg.Version,
		arg.GeneratedAt,
		arg.Items,
	)
	var i SystemSidebar
	err := row.Scan(
		&i.ID,
		&i.Context,
		&i.Version,
		&i.GeneratedAt,
		&i.Items,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
