// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: surcharge_rules.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSurchargeRule = `-- name: CreateSurchargeRule :one
INSERT INTO system_surcharge_rules (service_id, zone_id, surcharge_type, amount, unit, condition, is_active)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, service_id, zone_id, surcharge_type, amount, unit, condition, is_active, created_at, updated_at, deleted_at
`

type CreateSurchargeRuleParams struct {
	ServiceID     uuid.UUID      `json:"service_id"`
	ZoneID        uuid.UUID      `json:"zone_id"`
	SurchargeType string         `json:"surcharge_type"`
	Amount        pgtype.Numeric `json:"amount"`
	Unit          string         `json:"unit"`
	Condition     []byte         `json:"condition"`
	IsActive      bool           `json:"is_active"`
}

func (q *Queries) CreateSurchargeRule(ctx context.Context, arg CreateSurchargeRuleParams) (SystemSurchargeRule, error) {
	row := q.db.QueryRow(ctx, createSurchargeRule,
		arg.ServiceID,
		arg.ZoneID,
		arg.SurchargeType,
		arg.Amount,
		arg.Unit,
		arg.Condition,
		arg.IsActive,
	)
	var i SystemSurchargeRule
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.ZoneID,
		&i.SurchargeType,
		&i.Amount,
		&i.Unit,
		&i.Condition,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteSurchargeRule = `-- name: DeleteSurchargeRule :exec
UPDATE system_surcharge_rules
SET deleted_at = CURRENT_TIMESTAMP, updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteSurchargeRule(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSurchargeRule, id)
	return err
}

const getSurchargeRuleByID = `-- name: GetSurchargeRuleByID :one
SELECT id, service_id, zone_id, surcharge_type, amount, unit, condition, is_active, created_at, updated_at, deleted_at FROM system_surcharge_rules
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetSurchargeRuleByID(ctx context.Context, id uuid.UUID) (SystemSurchargeRule, error) {
	row := q.db.QueryRow(ctx, getSurchargeRuleByID, id)
	var i SystemSurchargeRule
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.ZoneID,
		&i.SurchargeType,
		&i.Amount,
		&i.Unit,
		&i.Condition,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listSurchargeRules = `-- name: ListSurchargeRules :many
SELECT id, service_id, zone_id, surcharge_type, amount, unit, condition, is_active, created_at, updated_at, deleted_at FROM system_surcharge_rules
WHERE deleted_at IS NULL
  AND ($1::uuid IS NULL OR service_id = $1::uuid)
  AND ($2::uuid IS NULL OR zone_id = $2::uuid)
ORDER BY service_id ASC, zone_id ASC, created_at DESC
`

type ListSurchargeRulesParams struct {
	ServiceID pgtype.UUID `json:"service_id"`
	ZoneID    pgtype.UUID `json:"zone_id"`
}

func (q *Queries) ListSurchargeRules(ctx context.Context, arg ListSurchargeRulesParams) ([]SystemSurchargeRule, error) {
	rows, err := q.db.Query(ctx, listSurchargeRules, arg.ServiceID, arg.ZoneID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SystemSurchargeRule{}
	for rows.Next() {
		var i SystemSurchargeRule
		if err := rows.Scan(
			&i.ID,
			&i.ServiceID,
			&i.ZoneID,
			&i.SurchargeType,
			&i.Amount,
			&i.Unit,
			&i.Condition,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSurchargeRule = `-- name: UpdateSurchargeRule :one
UPDATE system_surcharge_rules
SET
  service_id = $2,
  zone_id = $3,
  surcharge_type = $4,
  amount = $5,
  unit = $6,
  condition = $7,
  is_active = $8,
  updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, service_id, zone_id, surcharge_type, amount, unit, condition, is_active, created_at, updated_at, deleted_at
`

type UpdateSurchargeRuleParams struct {
	ID            uuid.UUID      `json:"id"`
	ServiceID     uuid.UUID      `json:"service_id"`
	ZoneID        uuid.UUID      `json:"zone_id"`
	SurchargeType string         `json:"surcharge_type"`
	Amount        pgtype.Numeric `json:"amount"`
	Unit          string         `json:"unit"`
	Condition     []byte         `json:"condition"`
	IsActive      bool           `json:"is_active"`
}

func (q *Queries) UpdateSurchargeRule(ctx context.Context, arg UpdateSurchargeRuleParams) (SystemSurchargeRule, error) {
	row := q.db.QueryRow(ctx, updateSurchargeRule,
		arg.ID,
		arg.ServiceID,
		arg.ZoneID,
		arg.SurchargeType,
		arg.Amount,
		arg.Unit,
		arg.Condition,
		arg.IsActive,
	)
	var i SystemSurchargeRule
	err := row.Scan(
		&i.ID,
		&i.ServiceID,
		&i.ZoneID,
		&i.SurchargeType,
		&i.Amount,
		&i.Unit,
		&i.Condition,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
