// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_admin_refresh_token.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSystemAdminRefreshToken = `-- name: CreateSystemAdminRefreshToken :one
INSERT INTO system_admin_refresh_tokens (
    admin_id,
    refresh_token_hash,
    expires_at,
    ip_address,
    user_agent,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, admin_id, refresh_token_hash, expires_at, is_revoked, revoked_at, revoked_reason, last_active_at, ip_address, user_agent, metadata, created_at, updated_at, deleted_at
`

type CreateSystemAdminRefreshTokenParams struct {
	AdminID          uuid.UUID          `json:"admin_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	IpAddress        pgtype.Text        `json:"ip_address"`
	UserAgent        pgtype.Text        `json:"user_agent"`
	Metadata         []byte             `json:"metadata"`
}

func (q *Queries) CreateSystemAdminRefreshToken(ctx context.Context, arg CreateSystemAdminRefreshTokenParams) (SystemAdminRefreshToken, error) {
	row := q.db.QueryRow(ctx, createSystemAdminRefreshToken,
		arg.AdminID,
		arg.RefreshTokenHash,
		arg.ExpiresAt,
		arg.IpAddress,
		arg.UserAgent,
		arg.Metadata,
	)
	var i SystemAdminRefreshToken
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.LastActiveAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getSystemAdminRefreshTokenByHash = `-- name: GetSystemAdminRefreshTokenByHash :one
SELECT id, admin_id, refresh_token_hash, expires_at, is_revoked, revoked_at, revoked_reason, last_active_at, ip_address, user_agent, metadata, created_at, updated_at, deleted_at FROM system_admin_refresh_tokens
WHERE refresh_token_hash = $1 
  AND is_revoked = false 
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetSystemAdminRefreshTokenByHash(ctx context.Context, refreshTokenHash string) (SystemAdminRefreshToken, error) {
	row := q.db.QueryRow(ctx, getSystemAdminRefreshTokenByHash, refreshTokenHash)
	var i SystemAdminRefreshToken
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.RefreshTokenHash,
		&i.ExpiresAt,
		&i.IsRevoked,
		&i.RevokedAt,
		&i.RevokedReason,
		&i.LastActiveAt,
		&i.IpAddress,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const revokeAllSystemAdminRefreshTokens = `-- name: RevokeAllSystemAdminRefreshTokens :exec
UPDATE system_admin_refresh_tokens
SET is_revoked = true,
    revoked_at = CURRENT_TIMESTAMP,
    revoked_reason = $2
WHERE admin_id = $1
  AND is_revoked = false
  AND deleted_at IS NULL
`

type RevokeAllSystemAdminRefreshTokensParams struct {
	AdminID       uuid.UUID   `json:"admin_id"`
	RevokedReason pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeAllSystemAdminRefreshTokens(ctx context.Context, arg RevokeAllSystemAdminRefreshTokensParams) error {
	_, err := q.db.Exec(ctx, revokeAllSystemAdminRefreshTokens, arg.AdminID, arg.RevokedReason)
	return err
}

const revokeSystemAdminRefreshTokenByHash = `-- name: RevokeSystemAdminRefreshTokenByHash :exec
UPDATE system_admin_refresh_tokens
SET is_revoked = true,
    revoked_at = CURRENT_TIMESTAMP,
    revoked_reason = $2
WHERE refresh_token_hash = $1
  AND is_revoked = false
  AND deleted_at IS NULL
`

type RevokeSystemAdminRefreshTokenByHashParams struct {
	RefreshTokenHash string      `json:"refresh_token_hash"`
	RevokedReason    pgtype.Text `json:"revoked_reason"`
}

func (q *Queries) RevokeSystemAdminRefreshTokenByHash(ctx context.Context, arg RevokeSystemAdminRefreshTokenByHashParams) error {
	_, err := q.db.Exec(ctx, revokeSystemAdminRefreshTokenByHash, arg.RefreshTokenHash, arg.RevokedReason)
	return err
}

const updateSystemAdminRefreshTokenActivity = `-- name: UpdateSystemAdminRefreshTokenActivity :exec
UPDATE system_admin_refresh_tokens
SET last_active_at = CURRENT_TIMESTAMP
WHERE id = $1
  AND is_revoked = false
  AND deleted_at IS NULL
`

func (q *Queries) UpdateSystemAdminRefreshTokenActivity(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateSystemAdminRefreshTokenActivity, id)
	return err
}
