// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_admin.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const getSystemAdminByEmail = `-- name: GetSystemAdminByEmail :one
SELECT id, email, password_hash, full_name, department, is_active, last_login_at, created_at, updated_at FROM system_admins
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetSystemAdminByEmail(ctx context.Context, email string) (SystemAdmin, error) {
	row := q.db.QueryRow(ctx, getSystemAdminByEmail, email)
	var i SystemAdmin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Department,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSystemAdminByID = `-- name: GetSystemAdminByID :one
SELECT id, email, password_hash, full_name, department, is_active, last_login_at, created_at, updated_at FROM system_admins
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSystemAdminByID(ctx context.Context, id uuid.UUID) (SystemAdmin, error) {
	row := q.db.QueryRow(ctx, getSystemAdminByID, id)
	var i SystemAdmin
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Department,
		&i.IsActive,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSystemAdminLastLoginAt = `-- name: UpdateSystemAdminLastLoginAt :exec
UPDATE system_admins
SET last_login_at = $2
WHERE id = $1
`

type UpdateSystemAdminLastLoginAtParams struct {
	ID          uuid.UUID          `json:"id"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}

func (q *Queries) UpdateSystemAdminLastLoginAt(ctx context.Context, arg UpdateSystemAdminLastLoginAtParams) error {
	_, err := q.db.Exec(ctx, updateSystemAdminLastLoginAt, arg.ID, arg.LastLoginAt)
	return err
}
