// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_admin_roles.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAdminRolesByAdminID = `-- name: DeleteAdminRolesByAdminID :exec
DELETE FROM system_admin_roles WHERE admin_id = $1
`

func (q *Queries) DeleteAdminRolesByAdminID(ctx context.Context, adminID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAdminRolesByAdminID, adminID)
	return err
}

const getRoleIDsByAdminID = `-- name: GetRoleIDsByAdminID :many
SELECT role_id FROM system_admin_roles WHERE admin_id = $1
`

func (q *Queries) GetRoleIDsByAdminID(ctx context.Context, adminID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, getRoleIDsByAdminID, adminID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var role_id uuid.UUID
		if err := rows.Scan(&role_id); err != nil {
			return nil, err
		}
		items = append(items, role_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAdminRole = `-- name: InsertAdminRole :exec
INSERT INTO system_admin_roles (admin_id, role_id, assigned_by)
VALUES ($1, $2, $3)
`

type InsertAdminRoleParams struct {
	AdminID    uuid.UUID   `json:"admin_id"`
	RoleID     uuid.UUID   `json:"role_id"`
	AssignedBy pgtype.UUID `json:"assigned_by"`
}

func (q *Queries) InsertAdminRole(ctx context.Context, arg InsertAdminRoleParams) error {
	_, err := q.db.Exec(ctx, insertAdminRole, arg.AdminID, arg.RoleID, arg.AssignedBy)
	return err
}
