// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: system_login_history.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSystemLoginHistory = `-- name: CreateSystemLoginHistory :one
INSERT INTO system_login_histories (
    admin_id,
    result,
    failure_reason,
    ip_address,
    user_agent,
    location,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, admin_id, login_at, result, failure_reason, ip_address, user_agent, location, metadata, created_at
`

type CreateSystemLoginHistoryParams struct {
	AdminID       uuid.UUID   `json:"admin_id"`
	Result        string      `json:"result"`
	FailureReason pgtype.Text `json:"failure_reason"`
	IpAddress     pgtype.Text `json:"ip_address"`
	UserAgent     pgtype.Text `json:"user_agent"`
	Location      pgtype.Text `json:"location"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) CreateSystemLoginHistory(ctx context.Context, arg CreateSystemLoginHistoryParams) (SystemLoginHistory, error) {
	row := q.db.QueryRow(ctx, createSystemLoginHistory,
		arg.AdminID,
		arg.Result,
		arg.FailureReason,
		arg.IpAddress,
		arg.UserAgent,
		arg.Location,
		arg.Metadata,
	)
	var i SystemLoginHistory
	err := row.Scan(
		&i.ID,
		&i.AdminID,
		&i.LoginAt,
		&i.Result,
		&i.FailureReason,
		&i.IpAddress,
		&i.UserAgent,
		&i.Location,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
