// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user_profile.sql

package pgdb

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO user_profiles (
    account_id, full_name, avatar_url, is_active, metadata
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, account_id, full_name, avatar_url, is_active, metadata, created_at, updated_at, deleted_at
`

type CreateUserProfileParams struct {
	AccountID uuid.UUID   `json:"account_id"`
	FullName  string      `json:"full_name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	IsActive  pgtype.Bool `json:"is_active"`
	Metadata  []byte      `json:"metadata"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile,
		arg.AccountID,
		arg.FullName,
		arg.AvatarUrl,
		arg.IsActive,
		arg.Metadata,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserProfileByAccountId = `-- name: GetUserProfileByAccountId :one
SELECT id, account_id, full_name, avatar_url, is_active, metadata, created_at, updated_at, deleted_at FROM user_profiles WHERE account_id = $1 LIMIT 1
`

func (q *Queries) GetUserProfileByAccountId(ctx context.Context, accountID uuid.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByAccountId, accountID)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getUserProfileByID = `-- name: GetUserProfileByID :one
SELECT id, account_id, full_name, avatar_url, is_active, metadata, created_at, updated_at, deleted_at FROM user_profiles WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserProfileByID(ctx context.Context, id uuid.UUID) (UserProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfileByID, id)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE user_profiles
SET 
    full_name = $2,
    avatar_url = $3,
    is_active = $4,
    metadata = $5,
    updated_at = $6
WHERE id = $1
RETURNING id, account_id, full_name, avatar_url, is_active, metadata, created_at, updated_at, deleted_at
`

type UpdateUserProfileParams struct {
	ID        uuid.UUID          `json:"id"`
	FullName  string             `json:"full_name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
	IsActive  pgtype.Bool        `json:"is_active"`
	Metadata  []byte             `json:"metadata"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UserProfile, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.ID,
		arg.FullName,
		arg.AvatarUrl,
		arg.IsActive,
		arg.Metadata,
		arg.UpdatedAt,
	)
	var i UserProfile
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.FullName,
		&i.AvatarUrl,
		&i.IsActive,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
