services:
  gogogo-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ..:/gogogo-api
    environment:
      APP_ENV: docker_dev
    restart: unless-stopped